---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./authentik-blueprint/ks.yaml
  - ./media-volume/ks.yaml
  - ./config-backup/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr/authentik/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr/authentik/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sabnzbd/authentik/ks.yaml
  - ./jellyfin/ks.yaml
  - ./seerr/ks.yaml
  - ./bazarr/ks.yaml
  - ./bazarr/authentik/ks.yaml
  - ./prowlarr/ks.yaml
  - ./prowlarr/authentik/ks.yaml
  - ./configarr/ks.yaml
