---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./media-volume/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./jellyfin/ks.yaml
  - ./seerr/ks.yaml
  - ./bazarr/ks.yaml
