# Restic credentials for the Omada data backup. RESTIC_REPOSITORY is a
# subdirectory of the repository PVC, which the mover mounts at /mnt/repo.
apiVersion: v1
kind: Secret
metadata:
  name: omada-data-restic
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:753zL8tV6JRGeF750s+Nq60QRao=,iv:dKH0ceX78BQlQ6kr7ZNuStz/cgXoqAPn9OWG8hgPgA0=,tag:qnvenWavbhVFiNkSDArsEQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:iz3Ihw5iQqwOL0bB0DsZf3sGkepYK8RgaqFBa4LgP6Yr3p3y7q1VyuhY+Q0=,iv:/scgQ/2oZyBTs2PCIYXC4ZajbfNqMji+7vyzXhGa0Bc=,tag:r/oy048mPUDcTIwkr35Eow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHhBZjdKT1cw
        NW5EeU54ZmFJR0RtaWsvc205MWVjT1BrZmljRnB5RUdLRC9Od1pPNjY5TFZCTXkz
        YThCQmovTHVzNkJJaThWbkxHR21CMktZN0crYUJIOGd5Vjg3MThldlM0c1JpUElx
        WXVObWZqWEtxTkQ2L2lnR1dzdmd1YXJRcGo1YlgvaGp1M3lyMk1JTmxaUTRFaUVQ
        V0xPaVMzaHpVZjBKdjJkcFBuS3pISmpjY0tkMVowZlhFbU5SVlRyaldveXQvM2Yr
        aytLQmI2Q3NoOU94OFpOc3Mwbm4zcG80QmJrKzRzcndOaXV3RDltbHJxYXVmcEYz
        ekd3aWQ5QUtTNHNDcy9oYmN4MHJjeDNaanM1Sy93aVJLS1B5K3hzWDA0a3d3NWJh
        NVJQbFkwWGNsYXNOS0ZuUXZ3VkFXMWZLSTc5YWZldURpakZzb0RhbmQ4ZXd6RVRz
        M2V6U3AwQVpVQ2xmaEpuWWF4a21vRWJFOXNIT2txMDlPbmRLMjZWVU5oTDl3dHVJ
        RCtKL1JSQkVtRU91Q09KTElOMTM5OVZKVVpWYWV2UUE3QW4rcmZ0amMxd3cra0l5
        QVF0RDNaUTRsQVc2VXM3YWxWWDM2Sm52UWlrY243VFRsWkFnOXFLWC9mTFJYMmJL
        ZENSWHIvMG1ob2pMdDZienIyMU41VVpUT1lodHorZnhFK3ExNUh4TzVJZWVWTCtn
        OC82clRBWkJNM1dNaVQvamd0dm5VYUoxME44T1J5SHZXQkUreGNBK3ZDSnZBNWQy
        bG5rMUd4Z2hQZjNhN2JnVzdVM3J4MG15eEw2OTlIemtLOER0WlZ5ejdpeVZnbVVE
        ZUlEV0Fxb21KMCtEY2JxWEVWU0Fxby9QbnZVRC9qY1ZDSDlEbXlKa1ZRU2R1TFdS
        UFdJbzVxc0tSUFNhSEw0akFwa3d2cEEzdWJCOTJCRlp4REh6TWgwN2hldWhrSUtr
        c1UySTVEU3lkUC8waGFvVEtCSGlNVldtYzl5MGIxNndzU1R4WHJqUWgxRVh4K0Zp
        Umg0OHRQcHFiRmNUS1RsMkxaamE0ZnpMcHdFWlZ1OWVxRWJoYVdSZE1LTnF1MmpS
        ZlhieWo2bEUzc3FYenVjYnFYTW8yVTg1YjhIck82RTJXeW9ZU3ZFMGNKUTZaR2F1
        ankyUW93Zmx4WGZ3SEJlQVdYT0ZaYjBCN05IVUNURjVvK3lTeFFtMXFyS2R5UlFq
        U3lGbUJZZTNiZnErekJrTkFEeDBMQ05qcU4xcm5pWVYzWTBCZzdiNnFDWm9TMTBk
        NUpWc2g3em1tWnpmd2RCSWxrVnQ0ZUxBTjljbkZOSVYzZzhNQXpxN3FsVlAyOExK
        SW1SZWRNTDhkVks4aU1TRmZzd1BlMVRKbFFJVEhQd21hR1p3MXpiRFE3UXYwNHFw
        L0phSWtHRVBYS0ZoZllXZlVWOWdlTjNzMWtMSG5wTDcySDFWajJqL2E4UEsyaVJV
        VTJnc3k0S1BwVzUxTDY2dmVYeFoxVTJpWmgwaDFxa21Na1ZiQVJBQWd0TzJIOWJV
        ZFhxNkpvOWpFTmdGaUFudWRjT0c0WGZ2MkNJM09yOWsxSkNWN1AvaXFQVjAvS1pR
        NFpnMFlGVnVsa28vSGxzek5CV3Z0blQrKzJTWkthWTVoMUJqejBlSUljM0gvS0dt
        SWgraWhQVzlXRVpBTWtVcmp6SXJsSHdvZnpWUmx4M20vcExseWUxd2Nxd2syak83
        Q1dNbUNkbTJtbjQrdCtEaEQ1S0lNakYzaDVDRHZDV2ZWRXBsd0svVThocUxkMm5O
        UXRQcjNoaFJsNXNuaFk2S29kV2hjSjhCRm1NVWd4ZElEb3JudjJPYlV5MUNOU0ZW
        dmFnZ2prcDQ5NTF6ZkptbWRRbzh1U2MyNmt1NU54eUI0WlJIeTNnaXVERFFwcXR4
        TGVGSGRTVlRHd0UzRWJ2UWJVWFR6S1FyZkNTNVVZYlc1S09CQlVsQlo1elNLUQp1
        OC9CQ3JkY0NNQnVQS2RuRHhLNmtnR055NUk0RW1PREYvL0tSRTZXY3J3Ci0tLSBt
        NVk5cUhrUEZUdlRnN1RzRDRmQXVGZXgwd1NnRXZzWTVoVTJhOEt4K0hJCgrFPuZw
        oAU6szTJGG5BP3ZyU1FRlZJYLd/+3pmMg92Qe0vWcqNG6c6LZv5947NoMjTXQN54
        5qfAh64B2xfnBu4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T22:23:27Z"
  mac: ENC[AES256_GCM,data:uRSfnUQ0QFoTcILhUyF9UByzo507yvqpXM2xX/nzW6S8/9UL9IBQGiQcOBPaNIkPCDNGgS47zZgq992yNkxjY1+TyAf855lopvOTyGHd67ojyZsmJprtsD5sFvHZorY3iZNJHYgbwlfvxXVmchX+MaUJMhAlGftFM8ytqBDn4As=,iv:C7L+qYxdQ8yl678iZEtAq/kTena42+YVGNwZc7TD1ZM=,tag:52XWerU8MTfLLGm5YZvpug==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
