---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: onepassword-connect
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    connect:
      credentials_base64: "test-credentials"
      resources:
        requests:
          cpu: 5m
          memory: 128Mi
        limits:
          memory: 256Mi
    operator:
      create: true
      token:
        value: "test-token"
      resources:
        requests:
          cpu: 5m
          memory: 64Mi
        limits:
          memory: 128Mi