---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-secret
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:PLACEHOLDER_FOR_SOPS_ENCRYPTED_TOKEN,type:str]
  credentials: ENC[AES256_GCM,data:PLACEHOLDER_FOR_SOPS_ENCRYPTED_CREDENTIALS,type:str]