---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./pvc.yaml
  - ./replicationsources.yaml
  - ./sqlite-snapshot.yaml
  - ./postgres-backup-pvc.yaml
  - ./postgres-backup-cronjobs.yaml
