apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:l6jt0LNfYr91BPlhAOaEl1uJa7GVfMhE1BfKkTHwrGSeGq0S,iv:a2ll5jLaQ9KSOR1IvXS7VBaQ+SgTstHDoM+vY5zM7wQ=,tag:MJ8MZwAI1PvjIxTAvzECdw==,type:str]
    credentials.json: ENC[AES256_GCM,data:LLdBIBGEza01+H0ZqKW55pJw0yddVaaOhEF3xEjz2srnzJy+uxe7LxgsAfED8HU2yJZXHO+mtoKiNZtt1aUyz3oeF5mMcPxG7sE5eM339ya9yKYw903yEDvBxBcgfP2rDQexxu+xOe9APaQaHLSyobC+tQ6UhmLGtwge1Nooo9YuJXIgN4twswUGrWcVF6gSP2rN+GBxYvkdstpdaX8okT+QfXPhfC/SzshFOm8Pew==,iv:G+RJDi7JT1gu4LlJI7XaBLSHX/4syEDxvw4zniUlMAc=,tag:hr3cwURtaILG60q4VsCOFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSGZDbURaZG02cnI4c2JE
            dFRtRHo3Y2J2SU5yUW5WWFZTOUg5dyt0MUV3Ck1WUFZadGc2OFVjZnI4aHJGNktr
            L3RRSFBDcWNqSjh1bUEwMDFyc3NaelkKLS0tIExhRHNLZEJKT2xGWTVZMFVxazdi
            OERNTDJRRy9nWHJ3bUhPWEFMczYrd0EKgnF3O7DHFkBPT9IweBJgrRWlLnmHXpVw
            x+SGuDQRmogZ3YZHzNeNhtmOG3WCZur2nDy1qEXQeMdyuFqJYEJbKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T19:45:23Z"
    mac: ENC[AES256_GCM,data:mCfzuYIF3OsMe4+vujOTI9yVJCf6PGe5lo42+6NylzBXTGRR/ZKdaJ6tVYDZtww4PlvjahaYZma1g6CK1idBnSAghlDIrVd8m+KWTYvbNnms2Kj+oXoe26LdOPSqDqObZjrq+HIu4SUJDFPVRsxRCa3TEvP2CSk+pEQrQOgs62o=,iv:sZs5NE5pU4L3Xs/WwST6gQ8F29xqi6lA1FkdYNm+SRo=,tag:VJ0rnV4VbZv9w7Fg8NIoLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
