apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:oNByrCMfQ5/xxQdL1O7/BnqN32SH6AXyujDx4pzjOXJfIb3r,iv:hjML6pU+9S89XQmDHtg1JMrw69k7AlKuG72GUX3f1Cs=,tag:f78sGHYs5uX1weryZeEJvw==,type:str]
    credentials.json: ENC[AES256_GCM,data:2TEWup5YdYzXxesmRqGZaRCYtfQAqkX+buFWmMBB2Jk5rku2rQRnS1HDPBUsiLXFtEdZLnx/j411V5xrnXyG4SwySDKydIc/TInQQs0IjB6dcEEZrY9JySJHQP1mA42PUM4zKZLq00tuVWxvvaVAn1i0zcIidqtTBcbKG0jp4j2+8BTSMuFaxRAa6VN8l189GW44BX4ZPFIr/2nGI7qaBlptBUnmIlWziFLcov07oQ==,iv:EuNKrdQRLsfVbVLu6QZxZyOxtDYreVXETWWyeOUtsCs=,tag:Sr/33Ngy35V6Y48OBAmvcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMjlVVVk0MzJ4WHRlYkNF
            RHk3Z0JJR1VHYi9vVEFYNFpNcTc5bWY0T1VrCi96S09ZRGkxeHhKeU1GK2dxRjFK
            T3Badks4cHlIY0dXUUl3cDhWQXJvSWcKLS0tIFBEVnhET2t0RzIvcmxqZkJHOWw4
            OFovM3BjZGlFWmNKVS9WbGFqWGQ2dm8KzO32RSTbcNhOGWVNsqhlNc3vJSNUy184
            uWejtqoCPcuWS9kF6iqbDt/P5Ahl02hFWtqLHpgn1ltc4Ph5fKyvJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T19:42:51Z"
    mac: ENC[AES256_GCM,data:8/Z169vsQ7d8FzEbLlkOT8x1EpEh3YCnVAPUUV3fm0zGuzjZknvTk2fsUhJYe4H1im3dRiF7aVHeCDi/UFXgTEuLVVgUk0unsTOdHDiL8eKEqZoavPKNxLGiv/x4L9vtXhlohGNNdJGWbQHHKXQ0VgSDF/fI5JFw4qJS67C69VY=,iv:kD7YmpKUkeiVK4BAZN7TeM+R0LiRQVJ1hq7wo9/yZRA=,tag:0N6ZuH4OgYqmLq1lRgLEQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
