apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:zhzeYULY0Cg2XV24eRQng4MbcHW8+iw1o47FDKOMkS3RKmqa,iv:uhehpvN/13PvjB8LK0u+uDDs0J+wd5Lpxo3frPJawZ8=,tag:Dq49bBttQY8xKefLaOLRTA==,type:str]
    credentials.json: ENC[AES256_GCM,data:TyA4f9E2tz/Whg4opbwE6T/PWunN87AXckwzU6zgwS9Q/iMUiexHKAcGqGyPSn3mQzZ9WD3fehsPpMkQhtTtS6QH/hTzePr2EfuyqNXURQsqEuIZ2bau4rDMZnphSjmD6y4XZ+UafZv9TEoxmrLNZt21y0zF1aydUOmyJAUXo+ZsHjP19Dj+LO0auqRekhot+HPG03mRUwDLJxsf3CSBDqTED3tfVCsec1FD+Xin3g==,iv:K27S/z3/fKc7pB7Rb7OgFxYt/JjY91MT1RoGf41TYEo=,tag:4IbW4TNFcMSE7KtWBR4Raw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbXVGM0tLQkg1b1hDcnBJ
            SXd5Z2NuUjdxYVhUcktkdUc5S212QXNGWWdBCk1PYWZscXpZMk13TEVBVFNXN1cx
            VlR2UGk2eXhZUWkrRHkxVFFyWDhOV28KLS0tIFBwb1FBcXlXaTlRRW41YVJiZzQv
            Syt3NnI4cFJ6NCt5REIwbVRCNG91Z1EK+ZjbhjSypk7I7QWoqwCIgxvYt/tO9E80
            dbMlkfa4uTDmL+AVA1NeccoiMHGZMdS+3JdZjqW6oblomIjxpY36uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T20:13:54Z"
    mac: ENC[AES256_GCM,data:2YWHMxlC7nuqNCX5xf5jyRBFbRbYAzZBNPSVzJD5Evn9cC2byLOmvF8HR1hHSaoBn62h0FZuEHFZ9OgPAtC+UgnQvmeJaQ/HvIn5EebaGzU7nuq7RNx0j1wtvdmaMNHyX6Jqueksq6mE17vH7QJwyyi2axR4VaABkxhXm5Cnyd8=,iv:GzrfVjR22I+LxPw0SU9es/xlPh2/ve5dkoLI+tVg7R8=,tag:xZ0nXAEaEtbVyq7uyi0rvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
