# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:/41PMAaxC3csk5sbe5NZgz0Th6wPrAiIGtovJ1VW0jucsTOZRCG4bQ==,iv:uP7ztcV1D3H0Lv37s8W3B2ptMcxCiafhe0gJKy9UVsU=,tag:kFGxtvZ4Rb8j48bg7L2eew==,type:str]
sops:
  age:
    - recipient: age1j822624yttmmve4h0ge5fu5ayekr7dcjwgnz73yspkdw8n2ax9eszyjs8d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cHdCa1d3cktmck5XNEcw
        US8yNDJlNVl5bURnNG82bDlzUDFPb3BJVzBRCmw0cExSMXBuU05ZbHhLelFWQU5C
        MDE0cUMxUFA3NjV4ZG9JL1BjNnBaNU0KLS0tIGt0WTQzQVRBYlp5eEtkeXlMdUxs
        VWc4R2ViNlRCMFBxTERNaDRPRWtOeUUKMLIuAwZAedd/rb8hVn3YQSgWdZYcC6F3
        YK7kTRyYXNDqxYQiUt3GtspKRh0nUJp6y+sDkpXW2tHszaCNKJ/seg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-19T08:06:12Z"
  mac: ENC[AES256_GCM,data:Ase0Q0FfuzurrfjIqAmO+0p/u7ralkA2rS/ys+/SQkruoFSOzhEyER24n73xZC+zHYVBXUFfBhNXZ9B6hcClJfwpSAUlasKeHoeAY/aJB9XS739V0Pq/XrKHYosEuIZE9jHaSZFpa7DuX+ZIdg6ppS90W1L7zxyJPJU1YiBBqRw=,iv:NQjHMjXGXooQW77AyQIHm/bjwN9/rnzPpoHKv4e0q/w=,tag:j9OFD3ve6HJ8H8QDc2LcHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
