apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fnP1ZZO9Up2BT4ajCeVwwR6ToRkEBmzqpPZ8zX1U4Ujz4A58XTWk1g==,iv:ehdtk8byQJbybnA372SuYvrp48l0618b3CIIikpngtk=,tag:ncVtcFH4mc2TIVKi/9KRxQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHZ3TFRIajY0
        TVRtMGhSMEVnQ3QwejU5VlhtYVh0bmQ3T0U1Qm9IZ3N5dWRFb09nTG1jNjJFdzdZ
        SDRZMDRYOCtqMFNmUFBjNTdFeEdXOE55RE9icHVNZm16amVhR0Jrc0c3dllqQU9E
        VU84YmtVWURjTUN2aElTVTdzcU9mTFNPTms2RWtBZHF2L2tSTkZzYlRCNUpRd3cz
        RHlNTSt1N0hhUHJYbVgvYXJTckxBakRJTVRxUkVnNFhTQ2t3MThpWmVNakY3b3pE
        djZZNHFKVlNDY3RuK2h4V2pwWTlCcjdHQlg1NGxiTk81RnUwOUM3cHIyeTBQN0tZ
        WUpZOEphQ3JKZlVUTzAvQ0twNWJ3N2U1UE93RFJhZi9XSDdva3ZDWWdSZkZvOFhY
        dnBvTzNNQzB2d3JQOWpVMGVvbVdjbm1hOUN3RXg1WjhxRDlKWUcvck9uUm5vQVdz
        VU1PRGZpTmMzeXJpUEpxZzlOakxKZ0FrMExTNzAvOG9KKzd4Z3NKQ0w5S0c5bkd4
        OE9GN3U5S3BpYWVuK1BsWmVDQTlZRDd2Rk1CNDVPZldtekFOTHYweDJ5eVZ5dWpK
        d2QyN1U3RWNhTUJKN2pDcGFwZnZsOWgyc0g1TTk1MG5HZ2xIN1ZkVFd1cXcxMmxh
        Z3FHZXhHSXhkT2JEd01YS3ZkNEMvY29YWFR2dkZQMEhhVDhYbGREUkloRVVpVnJw
        enBsQjVVNkNJZUEzQ1V6WVNxdFFqaXFiMTJDOHNROHg4UzNRN2s2SUR2blhBc1JJ
        anlSRTEvdWZGbzBYTXUveU1maFNkNHlDYjR5YStiR215aXVMb09tWnZYL1BLN3pz
        QU8vcmV5Ti83MW92b0g0WnhaQVJsRVB4R2Z5VFdhU2NQRnFML2plQVJ3WDVrVWkv
        eURLL0ZrOU41a0t2SFBlcUJlRmlQVHhwekVjNThMeDFsdFQzS3E0V1Iyb1pieHh3
        TjVBVWFjZ013bkpOOUo3QTM0Q0lGbFFiWlgxMzBvbnJqWXF3ZWNjdEF1Mzh3eTZj
        Z3BXTDZZWVg5NUowaE9IU1FCUHFxYUhHVExMa0tqU1E4dys2RkdFOTd1b1JRRmx3
        cDVRRk9hTWltTnJ4OUZ6MWJ3Y283MFV1N3huczlCOWRyWC8yVlRQUHRpNFhHVFVB
        U0E3ZUlzZWpLYTNqZlZZalZyK3hlQWwvMzR5VnlFQm8rVE9PRmRJRVdlbjlRZTl5
        cEZtVFh5Yy83cmVGZURUYklFUWpHakRDS242dnZXalB2TzVQUU1pOS9SZzFtZVVN
        UnAyOU9oQ1hSR1AzY0J0LytMK0JxYUpGclFGdE93S05vckluYVlKWmVZMFUvWVlB
        d3A1OVcwR3AxUU1uRElsd2hhNDIvQ21uUXZ0eko5R1RaT2ZPMDFDMVlseTVlK2VM
        VGZiZXpxWEZRdjNrZ0taMGExZGczUDRWWHVKYUExR29iblRBU09wYm0yNWxuZ2Yv
        WVA3c2ZqaEE3dG9yellGdU81ajA5bEtrVGZyVHNmZGFFTlJrMmIrVkVJWGk1SVll
        T1NJNWhKdm1pcGFwY2R4TUxQNGdBYXc3Y1ZtTU9TNXZKWGdoSms2VkZMWVd0SitG
        WDVjUHNNVVpPSEpnc0ZCcVNWRkRDMFRNbkxJVy9SZWRQYjRDTXFLWFVVTTVJRERH
        T2VrK3IyUFNSZjV5V0NyM2VIcytPemRtekpWUWpyVjczK1VtRWpsL1RzWm05RlhF
        bTg5WDNYak1ONFE5YnR3YXZRZjY1YVR2QXc3dTFEZGM2UmhuUmdsSVJ3SllFY1RV
        SVZHajVLNUp3T1pMdEV5a2NKZzVHSnJncjdnNllGeFcwTEZleVFJNVpRK2JXM0lo
        WnVOWXJSSzFTenN1Q2dDWG5Tc3lqZm1Cdmxzbm5HV0l4amczMC9PSS9sMDE3S29R
        SXpZQXgwVmVkMTI3eVFhZ1ppaDFHUjJZeUZtQ21QWUNaRmtRUWxVVUFPOTZkQQpm
        SUF5NFoyNEYyQUJ3UWZYMHUyejlpNmZGNU9WR09Ka2U1ZWRaQ2poemlZCi0tLSBx
        djViMXp4MTJJekZINW1yeGxYTzkwQVI1cVpZVDNoY0phcitmOEdHZ2dNCvQjcOBk
        xkPj0L+/4LvkVeoH7E/b6NHYU9f6gXcwYo/lJsruCse/VXTxW0oFoUxjDjyoLxsd
        pRfD3uWGbBe5tew=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T18:43:29Z"
  mac: ENC[AES256_GCM,data:WIla0bzzWs+0l04IIqIz9kO5g/+z6nmsfLr7QFYWZCD9rgpFeUP1TwSQKO3cNIpaR9H0BRPmtbNXOBtY4t+jbagSTwAR6Pa9VpXp2gXJWS4hFpHJnS2E2Mx6jJT6watcS22IHLH8I11dvbS1Hsxhb1xBFt6zoZAtqzZNYXpq3YM=,iv:zq5mqffZBMl8Z+3Kyi335rAWNf1TyG7sF4R4yqpqmJo=,tag:l7wCdaLawttsJ4ZBsvdgFQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
