apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:rQ8jUddg+ZtDz18j/BTioPBGiO82BDjAKMfkQ5ieDDGlaunyQtlz5w==,iv:9iSPlxOuCFX+wevs8gcz64YfbMhJrgDpwKzEauiWF5E=,tag:infhkARwfyHM8HBsPks3fw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDFkbjR0ZmVz
        THdWeUx4OHN5MTRZSktJSk9FakFyWVpEU1gxMHA4aGhKN1BXWFdVaTFQVUVveXQy
        SFVkZWNncGpkZ1pNSGtqN3JEaUZUY2RoQldQbVpWYzBvZFlWa3dXdm1GQ3c2VVVo
        dG1hZ1pDVXpFRGpsNUt2U1d1VVZTN002RmlTeFVZb25NZTZvT3FoRXlHNlpXY20z
        NUVlbFhJU25PMlZEaG1hMDJNRjlBSnFTVEJkTDcreTlvbi81TUhsekg5eGxOS213
        Z1VmbWJUZzNsTlB6dmtGUGJ2Z0Z1R056OCt6a2F5WFJLVEtDRnVtaXdlRklvR2t3
        bVh5VkFhOWRSSkJLbCtrNjhKY2JrVXl1MlpHOXlXcEdISEE0NGtTak5FRndjN05u
        YktKOHI2ZFQrWDcrcHlrazJ6VmpPbUZ4bjVOUzFxQmlFVEQ0Sm5DczRmUnpJU3M0
        L20ybEtUL05qbXNsOTJETnJKeG1mdzlqZFNiR0duOFRFem9ROFhDZFUwd1NxR0g4
        Yjc1UEtVMlJRYWxQMGdIdVV6d25vMVRHTEVxd2VINnhVdzJMZVRNam40UDYweGxW
        L2ZNbkxaUlZWaDc4YnhhVm8xN3BmOW5pZVZ4MkhGemNmN3l0TVB3NFJuOUk5cytE
        WHhxUk1VZVZ2R0NFLzRSZXducGgraktYYzN1Q3VIdythV1ArbDlud2MrQ28xNkNq
        WWtsMXdid2Rxc3V2dFN3eVpVUENTM0JXYklnM25vTDVET1E4Zjh6bVA5VXdPUWx6
        MEpjSmFtcDNDcXR3Wm9McG1KbTNBY0hYV1JnT0xCdVNTSkc3NFA0Sm4ra0tJcXBY
        MkxhaVVMWWk5TVVBRzlQaUxEbUk0YUlIcGtyK2xkWEcyTDVTV0dwV3pJLzRmaEpT
        U3J4d3gxVTVNcUZ1b3VzYm5POTEyR29jWlVlWDV6aXAxYmRudzVVVEZmQmpzQVo0
        WHdKQkFFTVYzWUdsYURtVnRIbm1oNmhHMVlOd05Ld081VXBNMTk3aFgweFN2UXI0
        WFluRmZMYTdxeUZvWlVQZ09qV3BMbEdONG9UM0FYb2dwRUlRSWVNK0g0MEQ5d05T
        RVRjOFlHRHJ6RE9kY3MyMWtQa3dOb1BSZk5CRmRyVm04eVZ4R3Z2MGFIU0pFcXN5
        cUJmcUVUbnpYaFhidWRtNHZGUytkaFZnNkNITWs0VlRJb243OWc5STlsb0JlVE9x
        cmNId1VJUmF6SXFsUDFndnd5aFJ4NnBNaFMzc01wbzlabUdWdUI5dzJxcHQ5cGNi
        N3llbVNkdEhQMTg1TVcvQldtSDV2NjljbTl1d0JncjE4UmdJV0tPWFhSWlVXa1lI
        cHVZenF2dHlDUEJXdzU0NnRGTlNuTGN4K1E0RDd1QjUvcTBXMk1jOCs5ZENnYm5J
        ZDhzdG9XdGw1aFZBOXpTVzVHM2N4YVQ5a09iUGFNWTdsdGNocUhwUFc2djBvQWx2
        UndJSUc1Q2FOeHNSd2NqMXI1ckdVd0k1ZVBFbUlwOVd4VlZ2VS9ob05BT3JNYXFK
        RVUzNllWdmEyRUU1Z1Y5RG1ORy9yZEJTeU5lZlZuTXA2dFBIVDlvVWQ5Wk5KNHdY
        RXlEV2FubStqWGtnbTk5Rms2U1oxc2M1QUw1dUNOVERSVGp0aG15enBNNlNOMXd1
        eE0vUUVNZERuVFBaZkhGaXljaGNtdWdJQ0ZoVUZLdG9qVitENVIzRlhMazg2b1g1
        ZkZJbWRRdGc3dkd4V0pEMGJFaU5YWXlwU2FhNGMzZCtHUDJrSDNkZkhmOWZ2UG9w
        TDNRM1IzQzEvK3ZJdG11K3pDVWhsekhLQmVBQU9lQUh0WjFWVTR3ckNDTWJLOUls
        ZEtjTmZmQWVpTktBZEYxVmRPOXp2M2Z6QThrdWpoY3JsTWo3d3ZPRjUyWk9ZVUhS
        MlM5a3dWbXZDeDd0S0IwK0gzaUx6WndBeDBaMERNeE8xZll3NVh3cmRyTzVJQQpK
        U0RnSkczc3FnaTVocW9TQkhFOSsvYnFmbWpaa1JOMHhWSTdSVExRT0kwCi0tLSBs
        YnpXRHZFeU95K3Qya2FTanpOMVNDZDBJVFhEejRMSEhPcjhpYk1zWXFvCkIGkZVb
        PCf5obcodnUtEmsGrH8YOBpoj0HxSaBP8NvJLjL7n2zgfemd5jmJJCYAhIrrxmi5
        1O6TPfD26wuQ/yE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T19:55:33Z"
  mac: ENC[AES256_GCM,data:hYgfaDcAr30JyBkaogzMnKnnk2PtSMZgw0YOjYNpTWCyeDp22nPEAK9xsrk05wp/Fd88cEF+73yyswEDsPW3qSyWiltZ3+0/tcY1SblfpdxqEBNN4Whv/t859ywzcpY1PSXMlduayiQJ9Uy2ImLO+NiPi+2CFbJQ7AUSPXIp9cg=,iv:MSc/zkDlfyIcpbR8Qey8mmGH5X9aW2FFqJGu3tpE1OI=,tag:P4YISxr3fdb5jbAHmXRaVQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
