apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:cVzw1EYp1yrDjIbEobaiIzSQKyKdovR4iB+H0hq2Ukhfs87gxTE1dg==,iv:tHbMPwNbEhJzdQPlxjL4Ra7kjEnfG1eH+4xpqf/sTVc=,tag:CJYeMzvLOdI3iAshlha+tg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFTUW9zSm5J
        clMxcnJNZHc0RHEyTUl5a2tlZjMrdjMxK0xaWUV0R2l4NUJTU0Z3akd4QktRb0dv
        Qk9HWFhSdkpXQVRZWFpuL3YrL0hvb09GUCtCMXhxeVBtdkRkUFdqb1JHK3N5Mmc1
        RmN5dXpjcEdieDRtdDVJZzZQWkYrV0t2U1oya0JOeHBEV1FuTkRONjR1ZjBmbnVT
        Zk1pQjZ5RzJJalEyNHhYOFRsRng5c2JDYnhSaEF3YjhYYnpOdHBEQndmcnR2OXJP
        TFYzWUdLL2NHQ1VISDc1L3Brb0tEbVhKZ0hPZmVNaEtZMHNxTkcrSnZ2a2I4ZmM3
        VjZZK0dhQ1ZuYWtGUjdWM2lqMyt3cXgvUWUwS1BBWWhZSDBzVzY1N2xuWVU1WCtD
        OGdtVDdSK1FxREE3Rkl3QUp3QnE2Z1cxV0MrbCtvSTRhVWZpL2RNYnZ2RUFHZ0da
        a3FlUmZaZWhRTUVDWWdTbjBWVEgxeXV4TFhPWlYrVzJsMTlWUWU3VHl1VTlhSXpL
        bFJuK2E1Z2dmRlpaeDlxb2pUeS9NeFRBWUVVWlhYZTMyZjJ5ZWtNVGQ1TXBnY3hC
        Ni8rTEprbjBlS0paM20yUmJIcDJ2dzV0bmFydThrckxhOVRQK2JYVWNRQ21qQno0
        d3ZBcHdEa1FjY3d4L3pBa3Y3YnRYZ2JPSXA3SXN5L255WWhHdTJGQzdOS2lpNlo4
        Uk5NVlU2b1Flb1lLYXNETXgraDh3YnRYTENFUDk0MFBTM0UrZWVVQWRLdnU5SE9X
        ZDZUejBVWDRXRmZJNkVUN1lMUkRIck1XTEovTTlxRlhNWi93aFVMTFdwd25tNGhC
        SnVFbE4wSi9jRHFVck0wdkdmOTJKQUs1ODNjcDJNaTFJRjcwelR3SEJZWGNYYStx
        UDFKaWJSb29CZllQcFo1Mmd6REdLWTJYcXFFWEQvSURpZG5iR1VQUzBBbjdFMzVu
        WUJuOWwyditiNSs0K2dMM3g5c3R2VGNGY0VsbndMUFVmMGFLR1phak5KdjBqNkZw
        bFM5WmY4Z3dXazdJWVUyL0RXa1BPbXdHTnNVVnlJdUl6YXQwb2F2cFZMMkh4a3pT
        eG9ROXA4YlpoUXhFc1dOT3g3aFJqV2pXLzNyU2MyUkF2SXZVbmttZ0NwbjkxL0R5
        RjBxNzNuc3MxaUtkeGJQQWxBYzdFcDhUV0JIUmpydWdDWXFvdTRBZzUyeEdJQW9X
        Y3JvVWxRV2g3VGQ3T0xsOFZpdW5wangycTRhSFFKTHczeWNIQ3BaWWJnNXZDTHhU
        SndmRkF4NllNd1g5Y0VRdUk0UElrWnRDc1NMQVk5WFlXYXJTS0d2Wjl2OC9KQTBG
        UXlTaTRwTEhscjNSWVZyTlRxYjR6aHBnQVBSQndLRHpJVGt1UWx5eWdoWWhaNHhI
        UFlGTVkrbGM4cFovOXVUM0NWM3o3Z0hLcXpmU1kvdm1pSm1ROWNEQXRlNEl6UzJW
        ellFb3lUQjdwbzQ3cXF5aUdNem12Yy9rSHNEeDdIWGd4dU9MWXNub3AwVWNOU0Uy
        N2ZKeUozWTZwMDhJNnlLWnpVaTBoUCtyM1JxZ0ZhQWxuYkNqdmVRWEFJdks4S3E5
        Mnp0S1ErVTZlOGoybHQ3ZVBGK0ZuMG9JYkJkZEFjZDh4U05MZG1pMGovcUtBY2h3
        TzJjK25LbGNmSHlwdnN3OWRUOUhacm5KZDJHMnJtS0diZzNQTmpwSFRrQ1k0RjJp
        T1VLend2ekhwODc1TlU1ek9ZMXFCMGdlQXB2M2tyamROWTZPSWlZV2ZFb0FQZlNK
        aXhmWWNqRzlZOGRHeEwyZUk0a290VnZqcXVvaERBdjRGUWNIditsNnRRR01zalZa
        dVhCMzU3ZlFrYktuK0pBQ1Yrd3ZwN0tGT012N290NzVkbml3eHBvcjFMbkxaS08z
        YXI4MEczbHFjcGdLK0U5UGl5dnVFa0ZXTXRENGRNb2FiMmlrNysvcFRMSGlVUQoz
        UFQ0R2gzRVgxdldJa1orQWsvUERnVGQxcklZTUs2Sjh2TkNSKytUVmxrCi0tLSBN
        cG1TVGpZMEtadU02cDNaTU9WNDc1STVCNHh6WHo0aWtsd2RIbGR0a2tnCqE1lbZe
        bA7Jbd0K0uxVVPj34uItk4Dg8KOi5GNqoKQmbtVoW87HPXm8Obdcle9A86701VNm
        /gTe/hsDRyyMPAA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T18:34:42Z"
  mac: ENC[AES256_GCM,data:tAubRPnKq9funJ7rVlVM71dFxn1n3X151Sp5lqY1T/LbNgh59mJciQg/Lbbi/xA/x20NL810jFOAcWdROFVhIc68LrdbCA0BlFrNpRXx1JnageSWQ9Pe4F7S8tITM98Um1Yr5cPQFSL14Q+TzsEoQfMqqHY78vDe/t1kR9Toer4=,iv:KdCw/QCZAKJD+n0wVwhk71/8cyHgj7vAlxQpkYCOw0E=,tag:N2U+ipSRHv29nVXL72D2RQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
