apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:pxMYW/y8,iv:oNWuk8qQ6Yi9zsTe3RNns4N3qGOD2WrYSRNAEjXYFsI=,tag:lHvFUEsU/JPux26wgq08Og==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDFCUmtrbnFh
        eDd2U081N09Dci9DSjBTeUYwanoyZVZaMmozRk5CSXFsbCtWR0ZFelJteDlZOXh3
        NkExUTgzUE5BY0lVby90alNUUDNrVlhYdFdBenFsQ01YR1JVMVgxblFiYjVyNDBK
        OGhuRXMyNWVvQ0pRbzAzRkdBOW5TZnNGYWtBMmlGWTBPekEvcmFQNGlZUC9HcEFT
        cDByUXRJL3Q5WTVjVGhSME1aRWdybmh6ZHQyUDdnWmwrQVRMUHNsSWJ1ekZHM1JK
        L0huMG93QmI5QmVBVFM3U01jOVVrUFRua2Z4aUdkMFNlUTZRY2U0RkFWTkdSbEtV
        d0NOWDZaK0ozZ1dDVlFmSDMxdHlLSXl2WG41aC9mSEFXQzBZeXF4V1ZYVHN2WENW
        VnZNa1dGMXlXQ2FkYW1zaEhxVVJFUFM0d0hWZW5wRnFvdVhzNUViNGNWZ0pyRS8r
        VlpHZEVFdjBOQVF1dTRDTjZPSEo0MnpCbXZEdFFmV0c0T0NyVmhlTElQTlk4dDlu
        NGpKeGlOREFzK1NkdmZlZXlwL3YrbVFvaWQ2VWZPcEIvSFNqUmlnekFVZldOM3Fh
        dUh6a28zNjFQdExMYXMwTERVeFlHRS95QmJGM0w3R0NXTXFMeEJhdGxUeXZxd3dE
        UTNDSVBoUHhBMUNwWlpGV3Boam44QzRQWmh5MVZhNHVCYzBSWnRsU3pIdGNzOVU3
        U3JWZ0lDYkxLemVJTW5nanR5Y3JpSHdtVUQxc3RGeDdEWXZZT3JWbjBycW9zaHYv
        RlF0Mnp6Wm8vVnlSUWtXWWxJdVRGbkhoYklQanlKZkZaMnBOTVpRMzhFcWNYR3lO
        Rmk0TnBTamtxYmxRUjFneVoraFphbEhjUUllVXhKRkJQenZCUStET3BDSUt1Vlh3
        VTNOR25leXJid21uR3lxS0lPbng1TzlaRFpjcmNISFZaeHZhY0tGUE02VkpUeWpi
        TEM5TEFSTmIrV0QvNmNOMTcrMjdFMkVDRWczYXJUNk5sdUE4WVlMaVo1Z3oyckxx
        L01QbTlIdzMyb1BMMVpKYTRiOHNFSjdqRkROeEJheFU2Wk1GYWRsd2lqb21lK3Yy
        WTdoQ29uOVhuYmpWWk10c3NtaWVJVEJEUUtYV3ExMjhkdlJJNmNIdVRpNm43ZXZN
        Q1RrQkszOThwYkNLTFZFYmR4TzRUblhoUkdDcVE2SzRSNG9ndmxCcFdoOTl4YThs
        b3JWMWtQdDFRUndReHpyaXoxQVppZ1BrWXNkMmdpaWovNDIvTklScXdJdXNJWTJE
        WEN5ajZOVEZVVmpFZDhQK1NYd1hwai9rdnVwVTNUZ3ZabU5wVjUvRldJaGJIMmhM
        QkRVRFVTU1E1TWRYS2dSM2R0RHNFSnBUS2FCbytHTHBBckpjQnRqQUkvaXNwdVJw
        YjVMa2E5alZnWXNZZ01IZUhtWlNRTXVPNExNYkRyRjdjSkczcjdCakFTaWlXay84
        RUd2SkFVcWdad1dVTlFrNVk4YjA0cHd5eUlURmxKc1VDZC9Nb295QS9rN29iNi9n
        QTl6ZHNLVGx3K1AvdWpaeVRSOWd6aXBENTZGVnY4WEkvajlyQzlWelhNWlRSYVJL
        eVA1K0NNdDFiMVNKZHp0UkxWSko5c09sb2tNRG90MFhUTzBGVFcyc08wT2ZZSUw4
        Zy95emRnZ0gzZVl5d3RtUkY2ZHN4ODNnZTJyaGs2djZqdWllelhmZlFhUmdTM1pG
        V2xCK2w2MFIrSFgweFI4QXppQytTU1ZzV0VldnoxeDAyUXIvMmU1QnVmSUwvTnJ5
        UndMbkttQ2RXTFdtUG10Q295emZzOEZBTFRKZ25vdVZPMlpBcDNIWktaaktlOVdI
        Sm5SbkVLMm9LY2Q1c2xLVklBUE4xYmg2cExjbldHenVHYm10a1JqZkdwTGYyNEd1
        a3NrbEJFeERFWlJOWkFpVUJhazQyQm9iSlNHaVdEbkd2djg3ZlB1a0ZnejhDZwpM
        SVdLUVQ0a3VCRHNoV3c1QmRQODJnZnV2dit4T0tqRFJBMXpTN1hSM3VNCi0tLSB4
        SmlHYW5iRzRVRXVxSmdBdVNFS0grM1hNeDNwbDJBYm5pRWx3SFB5ZGZnCrX2NHuf
        dRm2TOC5qHb3qSQcmxDeZZFYomkF+cS+FTpzhZS6MMmakpVs91HtU+XdFjLBWPtq
        pT3jO0ir5fkiWLQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T19:55:33Z"
  mac: ENC[AES256_GCM,data:zWvkwrOYRnZtJ/7B3VylanWEllpu/8vDcXJM7ryEh80+HBxXiqWg8jZin0iZoboNZXTBHX0Fn3f1utmzZwsKqA6o2YqyOYr+/8zhtp/4Z28nMqghci2HIwyAvgK91RZgCq155qG32x2d8+haLUxfkH8GTAqfYevQ3Q/RBZZ2lAY=,iv:t+dTtltN7vHUnykF4zUNoeAMR1zNv+R4E2qqgUFXfS0=,tag:jTsyL9xykycOEL6+oJy83g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
