apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:R3ca6AAJ,iv:MU5HpWKXzaBekrQ7Tx5ZscwckNqCKSODxJIFAjP0Phs=,tag:2+4r5jRp/WR6nxSa+J9qyg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICtrZlRnY2c0
        MHpwelczWEFHd3ErclphNUlZcVFKWWtJRE50SUl5eEFRYTVwN3l6ekpJNXp4dnBY
        c0lTVXRLRWxpMC9FbEJOUXhWYTZya1BkdGo2Wk4vUFJHMnhIdWw4WHBYMFJpSzZy
        TDBEVWVHN0Vmemh4R2xjakY2dkJFNDNVMVdZRDJ3NU5qWFY2REtYY1lacFhhWUw5
        TkVmRUZFSEIxMU1iVHEzSzJyNGc2czNJa0tFQ1JiQXF2VFM5Ylc1eFRvTUtaVDgr
        cEJhYlBTSzg2LzNkd2xOVFcwM1hXeVBIWnFITHBqekVnQS9lSlU4MnVjeFVkNmxz
        SDhlNzJFSUk4SjRNZUNvbDYrclJOWmgrcnBuNXNNMFhrNklMTXpJN1FCa1ltQmxv
        TWl4UStBWlFmR0NBQjlUdVU3SE9Gandvbk8xWGg2dDNGSndNYm5qS1lKM1BhNmFV
        TE1nVGlMbTNmMnN6K1JQSWpGM05hVjlrVlNoUE1NMmxnaFdHNXQ4UEdKVmZLT3BR
        QVJqWlFZUHJKWEdVSU52MlFuU011cXpWN0FhV0VsejFpVWd5WTdBRlVWRTREL2ZP
        cjZpWEVSbWxzUGRCRHNpMVJrOTdRNkUyODV6WCthYlpHbjFTNndvUndyVWhsb096
        ckl2V1BrRFlZOURhQVpRWnIxUmhjM1FaUW12VTNab1AyZWdCajVQOE04R2lyc1hP
        WWhvd2F5VFBCa0JoOTZubzdzS2c2czRwZUdVRS9MRGFvNS9BdVluNU9WWEtQU0RJ
        WTNtU3BpdjlHdHI3NExITHVROWgzSEthY1NNNGNHWWh2emNaR2g2MzY5bHpGTW9K
        Mk1zVUpGVWcwSW9uNFdtcG5vYkhETkhsM1NucDd5d1Y0N1BXQmRKUjBSUTZtNlJU
        WGtvbGcrN2VZSTg3elpEUTdSMFBsWjg1VkY0dGQxRytkTUpMT3pXRHkxNXpwTExi
        SEU3SXROeGNhaGx3R2s3VDQ1Rk81akdhY0JTYnBIeUMwZ2JWOFVHS1crakRvZjFK
        ci9QQjlOdzdIaEJGVFY3eHFpOW1mSnFHMnpEN1UxczdmR0tGVksyb2IzOWJ4RnJF
        bkFuRmJLV1BZaGNuWHJsKzdGVmtkeEpPSVZ4dVVBV3BiQjNDUDhnOVFEZEN4UnRn
        VUhUU2hHU1ZsQU9JeUNDUTdhamVOMmdhdEc3a1JNVFM2WWdzaUo5b09venhpdytW
        WXBXZUszM2Q0YkNOTnVkSGI5cFdZREhTWWl1SkIzY3FPOEl6ZUtQeUgyT1orVmNH
        VENRM1JUV0oyMDVBOGNnZFVDQ2RtTklSNHBuUitwL3l3VzByUUxnRnYvdlFBMzd5
        d0hBVWJsVzBQM0lIejd0QkRsdHdENWgrVmY5OGE5WkVwckNtbWp0RURtS3F5cDF1
        WDFqSFJwWnJSZEc1aVRobnZCZStIM3JoV0lGaWltejQrdmR3RkxENjBCdmhsZnk5
        TVVpYldmUml4bEg0emFBTG5za25BZm9sSXZESmdMZmdPSWIwODhlM0FMbWN2TG5R
        ZWp6bi9pZ3hFRDVvd3labkp3Rjc0dTkvN0FPbXNyQWFwM3dzTWt3Zlc2bjVNWm8z
        emdpWlVJci9yc05mMWIvUUprbHQwdWE5Z2JXbzBSR1VYZ21EcDNaeTdzVjUvK0w4
        YzJqeEU1RWNQM0g0dkVXa1pYWmxtUW1Dd1FZY081bnIzN2E0T0owYkdNVWpIRVJW
        KzBVY3k1NDNNNEx5dU9GNmZLT1dSTFB6VS9jVzJtWUQ2TEU4QWxkeHdzQlVwVSs0
        bWgxcHZRVkZHZURXZmpYeTFBM0lzS1V2ZWhPdmc2RVBkZHhLR25GOUFNVEVycUF4
        WTNreml5K2ViUnFtdkFDWFd3MWszUVVTcTlNYkY3R1IzWlFHbms2aUh4T1NPRGlp
        dWNnVk81L2xUby8zRFRIdy9zQngrZVIxVVFvZklWMzhuZXZ2Zm5UczBabkdidwpN
        OU5WdDF1UmppMndCSXBGRm80TDZrV0pRZVZaaWxrTCt0ZUNwaC9Xa1g0Ci0tLSBQ
        WVJVYUdwMXB4QWpKN1owY2xZTmVpcTc5VDRIWXhyMDh1RTNsMmNwVXlrCq78DvVZ
        TQTiQvWMVYyZq9C/u5luYISrVVLB2kf5evFYnw7XiBvUkIkqOpkE/0Z7leV7nMDF
        cui6eRB5//5yEUI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T18:43:29Z"
  mac: ENC[AES256_GCM,data:sNXiXp79zwDsOwPGmAwAocit8sr6HjF3zsbQXcuK7OMP8OLY88ukYMq6RIs9lnJAIbFonG3h1tFEjX90NW84yU1gaA3hJSoyy5YGT7CdS9B4SPEX5dS7zeuUgHVfG1jVS7kxjrScrzyjCJtb4wnPbET9zqFPI0t4qRFAgShs6Yk=,iv:t6++isWbwCmirIXj8lfYy2YcMFQLABqTK2OqJUeFHds=,tag:QdtXLlz/DIfdcyoCv+34lA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
