apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:k+XoR6JA,iv:XJ89bYBvBxxkUbWGjeVClNx+L7x3soLUoHQ9DlcKDb0=,tag:23tUvZfwvMjUJH4N+pSVDA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFQxTSs5WWdw
        MHZhbDJJL2k1UGZURVZoM0ptT0tVQVpUWTJMUm0vUDV3YlBWejQ4elBqdWhOZi9Q
        MndFVlY0MFpleG9rS09GOWgwMXh6Wld6YjBFaWNEM1lOR05VaDZCbjkrTlNPNUUz
        WVM5UHZ5NjNIcEVxWGVScHRBNmhVUWYrSmMreVdtUUkwMUx3TjdOTG9CLzQ4MUt4
        UkV6ekljc3d4MHhNOFgvZEtkYVRmbkZFRFJQY0tpNS9GL25iNlJka0pMeWpYUFBZ
        VlBhQ3B4TitYRVFXNkR3Q3JLM0JUTERtZDVudmJXRVFSNnZ1TWxYU1V5U0hKT3Z1
        dHBRNi9URVA4T3U1c1phOTdxNlEvbVlRd0lhd2J1YTQrRXNWS1hWL2lBYlZUcmQv
        K1RiZG9GVlpuNFg5NlEvZHREN0l0T095N0Y4Mnd0NER1aTNGVHlLa3JGSnFZNXhB
        Tk96OGlWeFdCS3BNSUFxcTRBSXNwZTU2MXRFTC9GQUt0SGxSWWZsOCtmOXZLMmtM
        c2Q0RjFkSEhQdkNjMStGZlNzc1p0ZmlqQWtTSGx6SG1BMEFmTy9sa2RneHhGeklI
        d2VCd2Vib01vM0RiTVVFVDUrQjREZlBpSnpKVk9pQ0xBbXpCNGVaSnUzYlVCMXc3
        MFBycis5dy9SYUhVb3JHMS9zRVRiQ0tSM3prOTBwS3ZSRkovTEtjT2ViYmdESU52
        cCtoL0ZSNHZEZUFZb1d6RXRsNXhtWlcxYkJxdU9IOFFPMU0vNXVwdWs4YjFFVzJw
        ZWpMTmplRHVrVU4zS0JuNHRDZzJ4TDgyQkppTEYrNGN3N3Y1dnNuNDc3SEk4KzZv
        dFB4TjBlcEhpcytTVm9tcHpyMytBSkw4WHdIVXc3MFBUNUEvZFF2aW5Za2s0K0xG
        OWsxeFpEblp3MHVYRGtiRHV0UUtMUCtmQyt6R00vL2UwaDBRREpDOE05c2pVU3c5
        RVVrTWJrQjltL1dCMTdONzAzR3VIcVFGdk1RMnVTT3FOSTRmT1Y0akhNUit3aXZv
        d2ZzZzdGV2F1YzdXOFBTWWtHVnNuWTRpR3ZyWXNyMTM0VHdBNk54RFM5bWZ0bTQx
        bTE5ZmpFS09OSjNXeVl1QVlnVE9Ldmd4am5HVWFoUU0xSGloaWpRM3JSV2N5WVFF
        TytiWHpZM1FmMFdyeGFaU1FPRW9NZ1FQZkhyeXZLTmZ6emZhTGFRa2taVkxCcWIw
        ZmxmVWplYW9hT0NqRW9wQ0p2bldxeStXRlRXZkNwelZHM1VCRm16VmJ2OWdENXM3
        a29ycEw2YkdqdnRTT216VlRUbVYyYXBDMm14Yk5rSTFrenBvZDVXMVJHZVFNVk9t
        QTVxZlAvNDlhdWNXRC83ZWRDeXVocG9mSFUrNGttMlpGRzVDWE5jbTFZRlBKU1Zz
        VzNUSkZ6T1Q0VXd3cG9SdFNMc2IzUGFYQlp2bWNicUVydjZ2T1lRd2cvcWhtQ0lM
        NU9XTnZKWWwrMmY2QlBUQlU1a2F0a0pSenQ0YUFmUlFzc1I2enRqYlJLam1FcHZE
        TVNhVU1RYUtHWHZ3ZmF5RUxVWWtGYTl4SEVXRDRpbkpNUWEwM0dTUlF5dzZuNkU0
        bEgzb2NaeHNMNWRMOVJiWkpSeHh0OVdSQ0hwNFpEQ1Z1aUhzSFlFUk4zTUlqOUhI
        aG1mTmVIZ3Z6cUNnQ1FWckowbnd2RVBFVFUzaWExb0NhT1dSajNseTRTR3JPOFY4
        emFtazZadjlUSWF4a0txUi9mWFNKcUZ4K1NaeS9tc3cyL3dUM1htR0RkNTJqOWdr
        K0J2VnNIZUlOYkwvN3NaWGNoRzZ3UVlNWC9Gc0ZRVjIrQzRDSXdDTHNJMTZRYzNr
        SmtRMUdKWUdhRnB6TkE4SnJzcVppYy9SVm9VdWU3ZDF1ZDlXdE0zMWUyU09ZKyt1
        RE5PSC9ocXhGbnAzQVhIWVRvT21VZjhNN3kwUmpjTVJlMWw5aEhuNk5VZ0xVQQo1
        MHVmR3ZRMlVIbml4MXpOWkN0S0FrSzRTNWgzbHJuVzZha1FYNG5wZVJrCi0tLSA1
        WEQ3OGU5YllueUdreFUwL3VxQVF1bThteFFpcWxGQlZ5QWlvT09vQXpFClZBlDZ5
        /g9gvZEEVvk3/C9g6O0OdhIOilqOL2iA2tUA1LdsE2sB+Hu0aSzgS9JxF64JiVZc
        3I2ukaZB2bYnIF8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T19:32:47Z"
  mac: ENC[AES256_GCM,data:s/m2u2SDlYb3Kd2ppa5t1A7kS4u3F3s3G56T09gQKpeNZdAnIS+j7b5fMXdNOvGO8hPkhuYCR2CkgzrQsPrrFxJGSIk6fRy2mM+dFh2IHnV0aRcXV2I/034AdFqQMsXoZ0ANGxL01nUN17cuqpHQ/pmPA1xHTFNKvy/ouPIuRfQ=,iv:HznEMoRicDF1tKBpituHFfDIaL8WiJWletYsUjasmVY=,tag:xiPwBYmz8jY+UfSWkT+eXw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
