apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:Jfi56gV1PiRZg6nVFvlxVQhsrnbwd2QA+ZA2UfWxSzI=,iv:O9XysFBcxCfUs6k+bngjLdj2GgP/yQS59b9h9C1Upto=,tag:U3jqnElHuGwcH7HeAf4b+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGlXV092YlFF
        TXZtV21TbzNEb3BLUHdReVIwZmxORkpabjBYcjB0UGRZTm53VmdtRzgvSDJTMERE
        TzdDVThyUUhPTGJ2MzBNaHB4dkhRTCtZUm5QTlVPc2oyTG9SZE5keU9laExHYk03
        NEN3UUZwbkMzdFJWZDI1WmxSVFp6SzdOVytkQzhoTUxlYTNYWUtOd1Z2ZEErNDhP
        dUVvN2tmWTNWMVVhenlxNGJ2WjIzelVOZjgvc0hXTmxwMEtuUnJEVzl3ZUNBLzh1
        Vk9yc3FQVEMxdVY4TU15czdwZ2VMWitLeTEvUTZ4dEF1L21XYzZiWmJnR1dma0hj
        V2V6S2wyRWZzdjIvMUw2Y0RWNDlQNGQzVHg4NktHRTlscGpCQ04rckFWY1JrUk0z
        Y0hCb1lZa1NrRzFQMXFJQ2xVbGJYdjhhSjUvMWNIQlJGeXFodGwrbERXVU9SdE1K
        WlZISXdURUc3ZTF1L0Z4ZDhGcmdHdDNJbmp0NDh4bE1hS2p0S2JRck84d09PWE1i
        UGZDZnNGdHNqakJCbUh1R3hVYnpqZVBQRHFHQXNxUDBZS2wxZ0JtM2JHN2x6a1Jj
        R3l1UWtCVDZqMDRidkZaa1VoaDM5c2tMNUhvSG1mK3ZWUFJUaHJEWHQySUtSMXpn
        L0lWeFlnMjArRlVDWmF4d3NLSUY1UDJRczZlU204UDhsY3Npc2NPckhuZUdPZ2k5
        MUFNSWRLejdZVWFhQ2w2L1hCUGFhQ2RzRkY3em96YUEwVTR0WFd6RDZLcjJqNkIz
        UE5ObXgzUDF2TVJoM1JUSnpWb2VocHRkbENKUjNYOUxIdFU0cWQrUWsxVUhiVzEv
        NE5pb2pzUzk5OUdpQUR0SktJOGNrN2lTVjBubXN4ZmxPNlhqUUpiSnZHUEM1cDEw
        czZOUUQvZEsrZHZTdU1sczBQQmtlK2s4N01Ib01IVnY5NEwxZE9MVHNRSUVYY2Z2
        cW1CaEpxMy9tQ3VZMDBJNXN5ZXlMSHgrSWZYaFdhSVN4S0crLzVUZTRXZ041UWJO
        V05YUEJoWlRHSHpKWWU5OHlqMlBPUUNHWXM0c2JHd3d5YWJpTUM0bkZjUm1uWldl
        OGJFZENnRVdheWlYSS9YVlRUbUZ4OWRORGRFUGQ3YSttejJSY3gyL1l5UlR4SU05
        WHl2OHN6c2x1aVJuakNlek9NNmpDcmlKVVk2LzJyeDZHK05US29BdU1Ld0trdTBD
        R1hWNzB1cEt6MFJ2SnZLWlcrMTd3NmdHQVlBRXFZYUJxR3k4eVhDZ0xBdGdJVmFO
        aFRzVFVNY1NTZXp3QUZwdmVjSkVGK0h0d0NLN3RkcXdIYWZ4enVKMHN1SEUrRnNJ
        S0FPUktiV2lkQjh4NC9BOVRJb2J1dkRVVzRFcmZxUEZ3NXc5QlJjaGV6N01XK2h5
        bHNzalZRUGs2TkxoWXdKc2llZGNhMmszZFNRN3JTbEFPbVRFODVPZ1FXMDY4Nnhq
        a0lvMGRBTVVMMnpvaGUram5xNUd3MWVSbFlieFhuUmREVVpHMC8xdzdORnNUWmI5
        YXpxZ0FqOUxZSkRnUlFNTjViUUxEVWNkN1JhSWtXZVdJY2tFVTQ1eWhPNUMwREVR
        b1p4YnZ0TGdsbEp2OTdHZjhNRjJ1ZFZyQnZVa3FPUmp3VlpPaU0ycGZqMHBqSEVv
        b0dZc29RUUM4THI4c1g2dkg1UWo3L3BwdlVUMkxZTVF2em1ZMkJDSy9Yd2lJVk4v
        TDVmWEJaY0V3YzBEY1hLS1RhaTg2NEJIaW5GM2RDUzZsMi9wVG9NclpRVDRTWlJI
        a2JUWFdTQVMvVEIvWHdYWmFkaUxacHJjMlNQRmdhVklOY29Qc1AxNnU5emt6MVRC
        QlJjai9kakFSZkJFVTM4UzhlTmI1ZUk5SFhSUmZFZG5PWi9OOXYvZkNqa0ZlZ3lZ
        elpGYlcrdkJPOHdrd1VVb1VKanltb0I1b1g1dE1zZE9MUVk3aGNmb1M4YUtWUQpY
        NU5mbmdCNGJmc3gyTW5UV3hiRnhjYkN4WElTblZveW9vcDdnNDkvbjBjCi0tLSBZ
        WGtzSlR6Y1EyckY1WnRvQjl4M0xKd0xwcm41cy9iUVMza25VRUMyaXNVCpYGwkdV
        cHAtCnDK4aJxcGLFYbroTWSJUO5cbt0snJBjFCCkij1wJlM/luxrhWv4K6jllsex
        sCG/ZgCnlK+aXr8=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-14T16:31:30Z"
  mac: ENC[AES256_GCM,data:wubYEpqvNFR1TaJZMoyDMP3lxb7FnOM103KD2ZTwje6XBG9eUEyEQR6uzqaXuydA/GCsBrgJHNnqdp2zkAHuPejWGhAvKY5LPIDs0rP0DvANNgWSXS3iBlJubGpVH3go1dFdtLZNnv8nH8VSgnd9ttjHzgbdLSDkBpz3ptHcBf8=,iv:2VXSjsAqLJm6Mev23f9AVx4qUJcL2XDRGg6WKp1uMlk=,tag:W085lCV8JPYQiIrjnQZCsw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
