# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wvWuRn7hcSGFqK3ClflLdRF0FJOGkRmh1IC7hbicvQ0=,iv:BMc3ghHiQCleZVBESqzk4lNQaUZeR5FPjcEFz1WTJxI=,tag:sG+WSJwRxx8/ltSaii4sNg==,type:str]
sops:
  age:
    - recipient: age1j822624yttmmve4h0ge5fu5ayekr7dcjwgnz73yspkdw8n2ax9eszyjs8d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dzJDYTJsanErYW5EMHNB
        UDV1bTNoTm85RlM3RTJCc3BjbE41bHlDM0NNClhhb1hZUXlydE9vUDF0aUpkOXZt
        U3Bld1RYSVl2VTlhY2xlaTg1Wm91NmMKLS0tIDZ3bDIwWVI3WHJTaHRubExTMk9t
        QnI3NTVScXRUVmdYMHdHK0Y0bEQ3ZmsKU4MbHamnZO1uEpwapHtRGbThVoQApg3q
        u9cntmNiQqzGM45nZtNEupyozmnJe2mrUHKmKlBOvSsfbfcB2AhDDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-15T14:18:54Z"
  mac: ENC[AES256_GCM,data:DQTtAfYThvtx2dBS8o1U6xZvdHhhog3KE8gPAdW9zfGG9pcsEAD+dIb54VJlVe6M4aDFB8sZLkezGihH6ZGJXNhKogtcfpKy8ugtmJ2LSoV6DzpY/EW/WkscyTxDCp4TkZHPW8zloCDcCAFJ/32/zFbXI/NF87rl7boFS5hXHlo=,iv:KGEMLClUptPXgXM6BFZYkbN2GPk3g/Esu3Fi+TJgwsQ=,tag:9q1xBNxQUXicMgwZnwN19Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
