apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:46aLFkJJ8lMfoWTjGQQf3K9NecueUlYCi3VhrLZut9Y=,iv:YGTbP2awzGRX8hRQYHcTCX57rD4S9obTbgkSqXl8TDY=,tag:8erJF8pnZ+2GsxPd2HsGxQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFFVUDByMkF3
        azhUMGRhMzlQV2VFbHJ1R3F4SzY2TTUzcDcrd3NIcVlwdW0zeUs1bGVVOUxMWXlL
        K2p1alkvNXNTMGxIOUxUeWRxVXdJRGRDNXkyUHMrTW1xQlBSRXh1YVo5c0UzL2pT
        b1hhbzk4RGRIWHpGaitRdGtaVDFJdjVIazdaWFVPNGgyRkxsVzdSYldic3ByVjBN
        eURQZVFaQ2hzdnVQUTBHcEhmbUUyQ1QzSThGaUJ6K2luUEI1ZjU2ekRDWTR6ZUx4
        WWRENG1nVVdkY2FUVEtCVWt3ZVlmc0NYTjhBOG9vWSt5N2plMDRqUmFrSHhGbFdi
        STVpWWp4K25oNWY1QS9uTVRLUUVOOGpJenRmbDRrWTR0Z3kxUWdKc084bWtXaTRQ
        aTB4MHRwdnNwbVg0N2ZVYm0wWTR4cDRJeElXMDhlQzZpQWFvNlBGZ1E0bCtDMGVy
        Z1h1RTZTcGI1WmZMY1RtUzBZWHh5WVZQRm4yRDJQYm5KTnF1eFo3Q3pHRjJiMnIv
        aXkzVDdYcmZwUFVYY21NY0p6b0xWSG93dXM3L3AzaXRkd0RYa2ZDYUg4REg3eXQw
        TEgwSUNIWE8wbHhCSThLQVJnSkdOUnl5U3lwclpDTktPTVBybTZwWUw1WDBNb2Rl
        YVBhRU5YRlE4L1R2TFEvcm9FaGMvZElNN0RCcURsOVJNOFlPM0c1M2puWHR1bWJV
        Y3M3UWJWR1Brd3VhM3pzcnc0S1BSWGlpTlFTZk5PMStXR0dNWW9WQzI4Q2hIdllB
        SmQzamt0emh6c3NBemJlRkdiZGpEU2FIcURFWTcvbFhKTGdqYVI3KzVDb09XOXlw
        eEJJQ2lWWGJkV2tEY3ZkSmgxNXI0Smg1VVZJc3NMOE1NZmZaaVgrOXJ0QlMvOGRK
        M2ZQVzFtcEdWRW1lSmQ5UEhBdWIrTkFUeE1RMmtiVlNteEg4d1dNSVRtSHRtZHdF
        UEJ4NEY1em1OTUhtc01HRkJqZ3RBUUZBY3RKVVpNeC8wOVdiWERvYlg1cEZkOUs4
        a3RDL3JuNGhCVXl1YnlJOW5neEZXK2dQMXpKeDlxakZOOWVjOHhwTGdCbUh1WlVv
        T1I0M1g4UTg0U2RMTWlsSkFZVlYxcm9pcjdSMjI4UGFyMDVBSjBMd2lSUHJiSlBF
        WUwzZm9oYW5hR1VtbXRRTVI5Q0E3cVVNSjRaS2VoUnByV1J6Z1g4UEQzOGk4VzU1
        UDh6RHdmYndqRE00Q2pST2huZ1BWek5oL2JTRTZuUVd2NG1UdXNxSUxFcllpaVJ0
        MFN6TTVFdWpqZGs1cDFYbGN5UnZaa0VQRVAvbWhUc09EaUZnM29kQlJ0eGw2aHVh
        anQ2UWtqS2VMaXNDYm03VU56b1hoVzdGSFVNdUdLMnZSSjFjR25oMlRhZHF6TWIw
        cDgxNWF6cHd2d25hdHd3dkJqanViQnFCbldIbnZJVnpVTFdySGNRazBOdjV4TExK
        cFBraGpQZEpMUWhOS3VmZHNKTmxkaDI0aStGaUI3WDNxT0U2VlpLNkhXTXduQ1p1
        WTVzb0JxUHJ4QTZNNmloK1d6NkRCa0hkU1Y4enoyTHA1ajJvSjQvRzVIMWRwaGpq
        anE5WmM0blplWWdXM3dmMlVnNEV0RlorMStCS1h3U21Td3UwM2tCZWFEclZISzFp
        NkRCOCtLQkkyLy9qaStKRS83d21mK204WFhiWldBNkF3YnVCbjd1Z21oaE45TUNu
        QUZhNnJRREpFVlBlbEFTMjEwSWZ6MTBpU3BGS2JFRXFKVTNNdGVWdUVmRnh4ZXJG
        UjdhUWZIRzRZV0ZTUnZtdEk4R2ZkdVVEOWZKZ2pYb3JjUlY1TmQ1RG5jbFRuVTlX
        dGplWG9vcFNnNno5VjB4Q0hPRUtUVXlLc0tOMks3MkpBZkFxTXJ3ODIyZlgyU0tR
        M1hnNGxjS0VHbThNQnlaaVBBOVY2MHl4N3NRYXF0cDluRGpaMHk4UGplOHBhUQp4
        cWo5UlBzYkFyUEhDcEJYZ0JENWs1Ty9kNkhMUE5jWitwWHg5VlhLVzJRCi0tLSBV
        azA2WC82dyt5MGViV1o1WFpwdkRKdUorM0pzUXl5NXB2VGRLUE52N0tNCjDw6EsS
        hJTaS3t90aY4vRG2U2kzQz9SEUboiBpRMmo2owz7sv/vr/z394zUP7lUazOJM8US
        Fpx+iunD+NFOBdU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T19:55:33Z"
  mac: ENC[AES256_GCM,data:WSeazFNw3YBWYT7WKAm9nJn4yAbYPfplxYCFKwYmCzlMTeTc29ZPxH+XLCxi6O0t2mMQcorFxSjCcazWH5peezHR+oTA8ZMAqOFsT24jyUdD9J3qI+JTQ7ArlJ9taJlvMx07vzmIFC/0lQwSPh1NWXeK2TB2pN3mKGprJUZkmNQ=,iv:zxj0OJkCbDd7K/pvlt4Z3GhdT3LxV1nkYkWmpG1J4BQ=,tag:v30M6DGhN6Sz162GW4lGew==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
