apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:KeZ8Z47qDHn8GTQxWduLcByqbVB6gLJYvh2MWqkh8As=,iv:r8N8E4l4bpXZpttBqcKUiSsiP1LPYZSf8hYIScPIk2w=,tag:fAq6xQW5emPQwmFGrY5wPg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEFHdTBrNksz
        V0dIUTJGbVRPU2xMdHl6OHlWQjZBcVV5ZHBxcXY0TTF1c0d5RkY0NGU0Rzd2QUE1
        NTRBekFJcVdyU0pTZlFmeGx0eXZidCtsM0xHamRWUUUybFNVaGZ1Qy84NFRSbXpG
        Zm05cG5EQkVIZDRpaVpDVHJHZTVsSEw5aTE1QmpQajV2T2RIWFFiUForL1JRVE1y
        NWJaOS92WXVSc1Z3NDFheDlZK01PaVFMMDVFcmo2SXNocEtka1AyeEFMWlJCN01L
        T3dSUFpMaG0rekcrWCtUbjVrQ0pFZCs4VGxKNm1leHRpM1UwdzBCNFpVRWIxajNL
        enIrd0JPb2ltcHNMVENGVGFSR3BubHp4SThzdkt4dDBQOGdSazVYVmV0bldjck9W
        SG1sdklKSWZQN0tWMWhKL1NMbEtCQjNYZlhOWkJIYU4ra2dLZm5iOEV6NzJvOEJY
        dmJrbGM3MzBsRWhmZ3cxMWFNbnk4SjF2WFN4eTRVM0ZCKzJWT2hzaUh0OEVkb1NT
        NVNJNDdNWDY0VmJjZHprZTVKQVRJbUFIRjU1NFA2YnNNemVWUDZMTDZFWDE1d2d2
        cHFDSDRvYmxoNjJBSitXdHpkZGxmZ25uV0pjbGJRMmNBdDZ2elBjV3ZzVDdNelRn
        UldZemhLR1M1cG9jaVM1OU9RZU5zUm1FUGpWS1hPNWJUaVZ6N1ZFNnRzV3cycTIx
        VE1EYzJnR1Y0dzF1UmxFOWdPRlFIdFE5elhHNXZBNHozY20weXdtSE5lL3RrZ3B1
        ZjhlbkFmLzFQYlcyOFBXYlFadmxWeEV0NmhyS0NOUVJRbTd0ZXBkdml2clF1c0ZW
        anRENHZkR0FhQk50eDRHZXB3emNUV0JKdHlWcG9oOGZOSEFtM29XUGx2NWNpVVU1
        MWtaUkZTYnVheVN1K1VSZXhqNUdvcld6T0dyRW5zS0pjYWl0VEM3L0s4b09CejlW
        cXRTWHZ0T0h4SmtsTk1ycjJVSm40RmNOODJvRUlTeWs2eXhYa3lQSEd2TWZJamxz
        M3B5NFhBckthUmNSbFJySTdISElwNXFoUWVuTXNkbXJUdHQrdWZrdlpxaVRlTUNh
        ajdQT1FXNkxXb24xelNSL1lvNCtCRmE4cXkvbkRIVnVHcW9FVVFpWHJpdFBPd1lE
        bHQ1cElaK3FRa3J0d0NPSVJXanJsMjhkbUhrVXR5RUZQMnJiRm53aXhwK0JHdkZE
        amFYUHBLaEZqS1ZvT0RDS0hPSVE5V2dLOGRZM2ZCbS9lWVVDUzdwRmpwOXd0K0Fu
        YVJLNDJFUUhoN2w1WkNXVGs5eHZlQ25qR1BZKytPL01OSEdhUlNrdkZPRVFaRzgr
        blJZVVl0bjd4QTN6cXI3Qnl4YUppdFRnQ0VzN21ERVJIeWMwbXU4Z3NDeGhvWUxx
        NFduZlJVOUFSdnVDdDFPc3VPdHcxSUJwWENFQklweE1oRjM3eU8xbmxDTnRxNlpn
        ak1ESkZGY1hxd2RDcWthQzBaY2JjY2xUZFRXSVduYVErSVpnN1dXL2tKS1JHVGFv
        NkY2R0ltRnZnOEIvUXBaZExQdmg3QjYxRjNyZnN2UnkvZjVOTXN4c0RKN2N4SmtH
        SHBpZEdFZE5XVnBlYnFUakhPcDRPeTlsbUFJSFYxVzJOZFBwOFM2ejFxVkRSeW9J
        R1RwOWpEbElSMDlHcUs0NGZiQkhkcU5KMEtKZWxIM3hUSGVPb2VXRFUybEU2clNz
        UHNHZTREaWQ0NUI3SXd1Y2ZEendIMFpaYzQycllFSU9OMXl5K1RvNVVXT1JwbkNR
        bHZYR01aQlVzbDdOblM0R2lYK1c4THdkbldUUHJZR0JkbzR2V0IzVlRicm13ODUw
        MFVIUStsWUF0VzB1NUFFUm9BQjdEVEs5ZjFaOTUzNFQ4QVczWENzVmNxazgrZWhP
        YjVUQ2RhUmVXb0pFbDlKdGczLzRXRkJ2MXU5U0E2OUpDUWdFSWRJZnJLTzFYQQo4
        cjA2d2FRbzFtWCtvVkNsK25XcUIyZ2dNY1Z4V2ZldDZJeW10U09jMUswCi0tLSBU
        RjZDQzZIM0J5QTFTa1k4Z3pLSmROZDZ1NlM5M0p1a0tFTXRYdWhLaHdjCjw3IrA4
        7STlGYKB51ZETEoekEWrKWhEfbun1uzr+0r7g9w87YXfh6VivEw1b87KipKJS/bE
        PqV0B4WlCdO3hAs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T19:32:46Z"
  mac: ENC[AES256_GCM,data:9RcF2RRpWwjQsGwzQ+U4HFwJ5Tp6okR7bGN6Mc4NhhlrCmff/N8ZC8T/Go9sIiBW33NUu2NaJYn0zLKm9YJ0Y7TmPAuhZiASwRPrlxajkmVNpAErgxPLlMUb6ZVpcf2o+wQsFIaLANiwWSK5tNhFRm6yqZ/dBsrv6H9Sh3jXCC8=,iv:ZkfLD6tAKV3490ObEMyqLeBpF2H0mrTtO/S3CNFd1S0=,tag:ZgFRvJfR8BCEHmBbAtqmcg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
