# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:3sS9S+ORff2b196MCR/OlOzPweJkQTn4NQj/8YWZpcY=,iv:gKHJSS99LL4Qapj4tzR75Epw+5cgAX3NcmBhP+gcXbw=,tag:fJO8guqE9k0KV2P0GtYZbw==,type:str]
sops:
  age:
    - recipient: age1j822624yttmmve4h0ge5fu5ayekr7dcjwgnz73yspkdw8n2ax9eszyjs8d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBelB5QnRLK2k0eGpnZ3di
        SDhvYk8vZlFmMEpsYW1IVWxPbk5jSHU0S1JZClpBb2RUZG0zcStFZlZzN1ozeGgw
        WWlyZE1wTGowQ043T0I5Q0F6TVVBYkkKLS0tIFFOVHZueEkwcWV6OTVPSEVaTnJW
        a2tBWHBuM3BqSUZWSGgvVGwvbXFvVG8K6hn+RX6B25qy0Tx+NWH/MGoMIyIP5KtT
        GOpXRMuYjvlpMAdMbHvuvfbXWDKHlcohmSRPmJz0eAj9ir4HwqdiYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-19T08:06:12Z"
  mac: ENC[AES256_GCM,data:IKxuIsD+8dnxRG/BMJAZi3eYdSxej71NGwQyllSBHIGgwDQke1ioAXumqnsqGVhMq4V6MlscvldZV1IpYdr0EsCHVizwfn/ZI6s/yD4A1CXW11IHBkqMiDOLZ0zU/eIXaVM8rwcx/X5sTH6+guOC0la1CS5mRyxC6Uqt5mG4yzo=,iv:htObENEpa0TTmCPcnIo9QSqkxfpIlN2Iid5BER7iAk0=,tag:yWXgLm1n8PSHadyphAXEWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
