apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:FOTKdG2SSkCStNTnimcovaqakZgkP8chhOMWT+UHJivCLiswvajfQA==,iv:CtNEKC1SWu4FQ8OH/ftM39iHem14xUFMnxcZHFckmKg=,tag:b6SNf7hXuTflePhdMa7dzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUFBRcVozeWEyQ21sTzRL
            cHFaYVRpVmlNcGZGL2R3QlRuSVlmRFR6YmtnCjNZSnpkcjBFZEp3cXkwSXVNN2Q0
            SjNuejc0dnp4aWZKdS9qS3ZMemJHOWcKLS0tICtabWJlL2JBcGdUcTVlTmt0cEhu
            V093OGxRTXV5SWhydkVoVm5IYTZMczQKvTgBRQvJe0DFdvIpZ0A+jEqB4nhRhyGY
            DfLg8T/WcQTI1vM72MNWRE3M5pvUYxue8RS185x7sVVQGt6DuJbj5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T20:13:54Z"
    mac: ENC[AES256_GCM,data:bAc3Lwqaiv2Ubzb1E4hyEhQBxp/tYuHIGYkR9Bny/qB8roo5DQZQsUqFWkLB7Thm6cnL9sGKt/OftcuNPf9NxGDIaQCsOoko89p2rUaXhLz9clcpw+RCU4SuMRu90KJk/iDwjYNpX0lh03uuMjhJHkoydbDV4bIvtgxahvnC/TA=,iv:BOt4LEsq07ceJ2ALsUdi7cYP5vSd1YiV+nqwy22kIeI=,tag:Y3TNZRhzODf/gLACw9PvNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
