apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:3k9KUDyelYWE9D4Eo0yHKJm8278oPETY78s4ibbP15vV0l6s0seI5Q==,iv:5XZKqTw206N6H+vlbq4eeHZgy7LTc7DLETJAo5VOzrU=,tag:RUkV02b88/6EegjL5ZL2jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJREtTb2xwWGVqY3pqbWh6
            SXR6VWRvaTdUenVnVWkxbUpxbVB4aVgzL1JJCnVkRUc2WjZiZFdmS3pSSEYzcU5s
            NUlwZ05oWlR1UTc3cThLMlZLZG1MSFEKLS0tIDhVWEFMUk9FWDZEZ01uS3owdUw1
            RDUwWmo5QllPTk9QV3g3dVRLTTZ1NkkKwyhrOn4mwWmnE7FhqnK8FAAk+l96XHyN
            NAPk8KW7vy3Vlbz7NoPC6EXGiqUVhS/1Bu2gV9+YlBV9MHjx/ErDEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T19:42:51Z"
    mac: ENC[AES256_GCM,data:EwpHcZyEpjRZ0ti9FLggyOrJEFwKKxD3S8Sr1SISQuBeNAmrsJ3Khhx3PHRt2E99vUnI5Ctg94shsAUmBrxPMELFc68FbMMmqZvYLoAoYxBhIEl2LvK9SF5gZxEkt9OLCAUuHGgL6FFXsH4DzAYAw9VrpwcWqWeoEBI6MwKZl4Y=,iv:QHn04FagDSV7Zm37j9AmG/3+yC56HWI6cOklosHeXpE=,tag:Cc6y4O4uyIGR1+YeBuA9/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
