apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:SWBh08/pHBC8UlWnMiILc3/zQbVH3o7e4jf4FHEoKkVpsQ7Whj4p+A==,iv:H0QDeUaeas2cGgua1z6IYKArNkMYfTbZ3muKBCD4SeU=,tag:KKHpZBo4BcQRvJCZ0o8XoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aHlyMDhIei9jNi84ZGJO
            Wld4SjZDTlh6TTdNSmdDRTJwMENlQ3hxNUFNCjVKNGt5MlNZUXJqQTYvZzl0ZGt3
            MWs4dU9ZanQxZnRFelF3aVdKN0hFRFEKLS0tIHF4bHBjNlk0TXBVSmFvaFhmaFdx
            ck5VM0RIRUtBQkM2YnlpV0pUYkJaeGcKTXXpYUPqhPiEez9p/R1UNxdv5lv/lvK6
            bLoqqjhUoX6/Fcg9ISH4bHh8guxaefEP8R3hXH4pQV8j0PXf2S/8ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T19:45:23Z"
    mac: ENC[AES256_GCM,data:ZXhlSmyNaUbmxpgfvg0Z7/d2UzsyVcSoR+aoBzyvKi+kcyGSm6uAUFylydnOA2PaLqqDF+XwpsCpKemwfytH0I4cVde+efn8HX8xGdiocQAaclzNJAwbPksggI9AhkEzDXjTKOcjYwJYj4pC1GlA/Qy85jXIZKAPegG8szCtooQ=,iv:VVB8HBR2ATV21iao+IWCsEoazotYtpUjuz6q/IQms20=,tag:qZYfKINmyN0KWgMHPeN3FQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
