# The ntfy topic name is the only thing protecting this channel — ntfy.sh has
# no per-topic access control and this repository is public.
apiVersion: v1
kind: Secret
metadata:
  name: gatus-secret
stringData:
  NTFY_TOPIC: ENC[AES256_GCM,data:v+5eWx/AqM4ykedTjz2CBCzL0kDLvgJl,iv:cs4Cs9f4LI0hwjLenQzetuZEf/2TMu35z3CyETkLySg=,tag:htYIP9FyEejcRAkZ9NOTxw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG5IdVptVFpC
        WmVlVzFZTGJmdmE1SEh5TlkyT1BSYmd6R1RFMWtGRTNDSk85eGc3anlRRlJxT21w
        SVVkUkRRWXI5dHJoTDFtbW5uWU9VVkhpdVNwalpiU0ttQmozdU00cndCeG92Z1BN
        RGNJYklrcm1McFMxblBLWEZjSHl5YXhhZmp4NHZ5SVNKdktrQzV4RmtxWjF0Y0o2
        T2dQZXExSzB3eTE1V1kxM0JtbEsvZHFNMDRrQjAvcjdhMi9ieEFUTkhDdlBTL2Zy
        TnBHNGZCRUFBVzhMTUxhRmcxcG1zSEoyS3RzZUYxb2tzNFVwemJTNXNwc0JjRDZs
        QjBobCsvaW03SEtSTHkySUVlUWNwYTNtdmtGS01UN2hSajVRSVJtRUxvQW5pVHJX
        bGtJaWJzQVh5VURFS1lHd0hYeWJLdjZ1RU5ycmxhakY4OGQ0UUphVkF5VUdpRmxi
        NWdlRnNqQ2tydmd0NXdJTWw4cmlBRlQ2c05OTlJCclBhQTJCQ1prc2ZyMDByVW0x
        WXRqLzJiZ0NXWTBOWXVPMUZBOEt6Y1JvUkxrVEhlSGRzNk9MbVBrdUV0bjI0SkhZ
        SmNocE5HN3BheHpuMm44WVF1NytqNldEN0JwTzhnSXl6UU1LVmpUS0RuMFppbGlW
        Um5HMW8rNzdzQTJ5eUVLRjJ4Q1AvN056SUlWUnU5eGVWdmlmVU1JdkZNRUIzdGhs
        RmJTTzFxdjJWVW8yajdUTTZnR2QrY090dkJYYTlMTTMvZU5zU2xxTTBzK3dLN2Zx
        bW9yNHVhS2RCMm8vVzRaRU1mdVlFOHRiV0xveUxseHBIaG55dkl0WmJQMEozSWpB
        YTc1Z2RuWVI5aUpxUk9KWExDd3RoSWJDcUI2bU5NNG5nQ0xHcXp2d1pqTjV1dXFC
        SVNhOGw0VVh2bldYWVFBUGZLMHJmUXZTRWtCeDQvSUs0Vjh4MWRGdzFUYmhweE5R
        OUNMSTJ2VmR3TDBOWk80SG1NSEQvSjFKdHVYVmtnSVRQdzBLSXB2QXNMaysxbXpF
        MTJBVE1BSStLNndXbkpyYjhoWXdkTk9HUC9jN0xoU0xzMWpLanUzeW1DaEpWYjJa
        YXMwKzFQY3NlL3VBWDFtMU54RWFuNXp4bllybnlUak91bWt0WGZPVWZ2QWZZemhN
        UFVtOEN1ZGZwait3aVdJbFlYOEYxYkYwUXNjczNWeU9KZ0YrS2w2dHZnUlpCYSt6
        TU5yT21zMW5vSTNXeWhheDVKOXdVUTZZaENVVVdCQjhWTS9pSE5ranVhYVNVaFN4
        RHBnVVN5bDVMZE85UnFaYTNxMGs2c05lcXY4em55MWRwL0VpeGFxamFobi8za0Ux
        aTRaclVDZUpvaXg4dmQ1M2hkU2FzL1p0OVNrdWJDNWFxb09seGVmOS9EYkJjMXFT
        M0xLT3JZc0l4clFLSjcrTHZVeXZQWGNvemxVQzlyOTMyeGR2aUZWSWN1azYwbWNM
        dzA4S3VNS1NSVWRJV1p1bmQ1aEpEeDZZS1p2UmdXRFFZQjcrd1k5Rnk3TnhmN215
        b1k2Z2I3ZUcwdGQ5Qmk4WU9oNGE5Smx3czZhZEFsN1FpRWR4Qmpkd0RjQXJveGt3
        WVZtcmFHNHV3MHA5b3NRRE9vVGpnanZIWUpHc2p0c0F2cjlrYVNxK0RrbWkySDhW
        eXIxbStySEhIandjc1ZRdWdCRy9pMlV1NFBwM1hGdCtDM29UQnpXTjd1Wmk5OVJt
        anhwRGxQSWlhZXJWQmdFNG9wSmpGMHA5YzUwb3ZvVkxUdmJJMWYxVEZGeTJGUDJi
        c1BvSmVIS3ovTk92bjNvcjl3NzM2KzlmbUVKbEQ0S3JJeWI4Q2VHTTdodUNkTEU2
        cVF6R0g4cUpXaHgrTFZmSkJLWnZsV0tObTgwRHhYWW1iV24wb0dqbnN0eXpoQm5P
        Z2dWVW40ZUVERUFwMDh5K29QQkNoWWhyQVBqUDZxQWgwMnd0NGN5Smw0NS9TUQo0
        L3Aza0t0anhmcWg5WmdPdGxCMFZEUWFMdWFHbE5JbVNlWFNNMnBrNWlVCi0tLSB0
        TVFuNTREZjR5NTY3cHZ0Ymg5NFVrTGRJelFMN1FWbll5eWV6WW5DQ2RZCvIQcnl4
        dFHqjs3GVx67b83fmGnh5bWwxKmTgjLOci2ZIjh47BLSfz1mh3BbhOyspF0n2S9t
        0gWbiNrsFOYcL8U=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T17:02:19Z"
  mac: ENC[AES256_GCM,data:LA6gCKJRashyE6duig4RuiJwurgGqOAlmugMxihLgl/j80cn8t4fMBgHVsZiZZBLzLsUnBPn+aXYi8RLw+kdKSo077krP5QNBe3i6C+bxPwxQDq7nSS0g6WxYlQ34OEyRRWWq7svHDi1ACThSNX4iSEO5JyNvSeJlNa+g6CfNB8=,iv:gtacsOx0bB+jbhlJII6cF9oDwJGWSQTPvJ0zqenFPp4=,tag:vCYqdnH4xM3MMW11GUVHjg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
