apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:HNVzbqzlMqp6wBlGvEshLUbc2//CrTeGRs4v99FuEAlN88Nt1hTt+a4g0Ea4RgXrMIgBgWwP/FR9/ueiza7HB1HOm7gr5J5ePYRf8rXK8HpfgBarKqXF8AbDVumQzaK/zdgKw8Oxhth65imyMRkQOVrWu8s9R3luVmsIMHdC8JgoVlN4Vd6BtlTYewOojsE6AYRjUe4GITFD+mt6yiVEWItdtDncrLI3QozRisdPNtY79T7U,iv:46TYjwf62g+Gi9Afw64SNSVjwgNbMcVTjlQ8Fv+Ifxo=,tag:S2gzBCCugpWnTBXFKFUm/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDMxNFZxY0Vs
        LytkMmpYSGVDU2ladzdSUDVOUk9uNldhNyswcTRCdXg2N3QrSDFURmQySjVDbm5k
        WVdKeHV4U0ZKU3Jvc28zSXpxT1R5ZWNBK3NWeERwNTNSdVhRSzA2RC9FakY5VTVR
        VGNMN2VWN0pPQ1NVdTVHWkVhVTdMV1Zwb2RwekRaQTZTamRPL0wxK3NrbE9ZQWVK
        cHNpdnV0TGYramVjVVYyenp3eFNReFk3N01ZRWxLNDZ0R1ZINzUwTXZyZFcxVmZO
        MXpPNFB2REt4djFybU01NXZLYnVEaUNSU0ttYWtVWVUrUWlra1VDRjR2bDRsS3pO
        cFlQNlJDY0x1aXlGaTd5TUJCbEtpbmQxSjhPU1IyRFdaM2ZnNmloSlE4Z2htaFZ1
        S1kwdEZNODRtVFRqQldYWkhWSk5YQTIvNE1QK2FaN0hWcVpnWklZdHNTTk12ZG8y
        NnRSdnkwRFpHZVI5Z21xc0dRWG1mOW9hUXMwanVNOHlUeVZUdnhxTTRtZ25laVND
        U2VMb2FFaHBhUlZyejdLVVZpbzVYOEt1L09qTEUwTnRsN1FldWMyd3N4WmNIcVEx
        czUzUXZlclcvMUlCTG8vS05hOFB3VEFTQ29pcFQzNW10Q2xqRFU3NndmRHdIOVdC
        Tk93SEtrVlpMNXd0cEdPb1B1bUo5WTBnVEE3OG43Z3J4eGMrTGdleHFUMDVKSzFr
        V0NCN0U3MVhpcWFCdUtEMWJKUyt1NmV0aXJsQjdkeW1ZVWhkRS93QTBVMTlobExE
        b1NabGVCTzhRRnFidm9Nalp1RFlxaTdqSjVLdHQ0OEtUcXdQZ2FYOExQZURydlNt
        NVRLNFpBWFRMSExYdU96dzJJOW5oN1FRRlZlR0VraVdLZDNmZE9oUlNRbU5wZDFR
        cCtyZU5yRmRtbjZoMU5HTy9FSXZPdmVGc3hlRzdQZlE1YjFkdzBEdktNQTcvYWVQ
        akh6RkUyM095WUtOZ2xTYXo3VVU0OWQ3elE4Uk15ekE2d09ibkJ5dVY3QUpIRVFo
        aWFIeDcveHFiZG84L1ExQVQ2OVdOY0l0dGM0aHV5MFVEcG5vWVFGM09tSGR6R056
        RGFucUhJNDMwM1FxVEFLdHFabjNVc1l3c1kvSHYzeVlwRnJrcHVQeFRIcDltbm5y
        M1BUM29rWC8rWU5UNnFtLzF3RHBwNWtZMkpmZjZiVW96QlFnM1FjZXF4OUdRczZ0
        c3JjR0xYT1V3QW5UOUJibldpU0tJQnlORGdWRTI0a1lDQjU1VUNaRUgzZDMvZUtz
        TlNNNlRFRzJhZUZ1RzlOVXZLRTdKOW5EWWpqckd6UktUTzdKTFV6V01aMFBlUFZS
        eWhOWkVIQXJzem1ONmFHcHlZUGhkYTJmVlRGaXZ0Z0tGdWxuVjhYcytiZjlRY1Fv
        akNvUUxtZ3ZxUXBHU3dVeXpoUE9mbzBsM0F2eXhtWUJnOS9JV2pBV0h5T29pWUho
        Uk9aQ0RCc1Z5VWtkWmZWczVyMWkwSE0zc093UlMzNU40UCtLNVdhNFlVZmhGbWpZ
        RjdvL0ZwbWJkUFV4OTZlTEFVSjZQaTgyN3pDTFU4VmVLemJhMkt5RkZhcEtEaG9T
        TCtmNG9DdGNjdHdkUU8rYU5yVlo3aFNsMkVsVzRZSDBET09abDh3TzV3VGJSbVUx
        N05JemF3eDJ0QnZ4ZERFdzVXTE5jTDcwVWlKQ25HaFE5d0pPUC9oM0dLWi9OSkh2
        SzNnSWZvSlNBZkVkUjBnck93QWJvVnhtWDJpNmpIVm1Rd0o3NmRPU2hXa0UvYkNr
        MTVzYU9wSzB4b3JrSEFTR1RpNXc1MHB4UklKZjZrQ0V5MXhpNGtXdXJ2RUY3dE14
        VytjTnYxTEZNZGxmc0pnUFZvRG1vMEZXS1pIVXkrK0dVdXhqRXNCa3VkOWxlZEdh
        bG9qSmtrdzE3Yi9JTGt1QjlTeFY3KzQ4Slp6Y0JBczJtRTJGazdJa05tYmdTZwpm
        cTIzU3RmekpxRkdsSXFLMk02cUVJOGlrR0o5b0lGeXRzTzZiclBmYlRvCi0tLSBX
        NStIT1c4dWtEQVNVY3NKVUJxdGRBNEU1QTJlR0twTmEvcmNJOTZGUzF3CmFsaAOz
        6I7YVLXzVHypBc1/rFAgypFZRnUQqz+1NKE5dFkUdDXh4/J37IKPYomBBDw93l8V
        CZyhYJCQvEPrWVg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T19:32:46Z"
  mac: ENC[AES256_GCM,data:OUKsP6N3q76hX+Wrn9wlSMl0uCvVYzqibjbm6cOGuUzUf300fyeIQtEzSEyIA1RaVbvy9PmQ65Km6IIxk0KvK0RITJixoLum1l17rQrDCGKL475OTKTiyRA6j9TD6yUt6TEu0Z/2bNCNvagkT97PvsRPdGkr2QiQmP5NnI9mVmQ=,iv:mMpEaEUQKEekcoJKpefF9o2VPWLctOXCKt0KdjB4IB8=,tag:FY8c5clpDM+HphRl3tDwrA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
