apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:qccuAvmEbUz0MnSLryZPPvu0qbcRHY3c2VZ+nA4mQZQp1PSb+1X7gzz2Eu6u7ktn3aX9Dfp6aUukRrIaqcubFqOdPNT8BSx/DSSOqoj+0icQacv+1igN9KYR+tb+vO1eKyQMCSGmsCKJTU31iEAiYlva9mffaYGSbam4lPyDy6kwiuLxXigESxvJkFhvekETxkONetkaslFotV5FLiwkf7gXcjjqPjqye84XJDjr+oKqyncO,iv:rQzhn1f6H/J7Ls3aOETTClWIBEW0C2zPxgrrfU+/j4A=,tag:9fcwPelKYRaU7Ep5x4kbNw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFpLU3c2YmtN
        aGFCZklJKzFVa1RsdWxKNWJwOGdOS0VGOEFrN3dweHlVWXlHSHArWTI4VW5LQUhJ
        MjdCUHl6UU0zQU1mUXZ0OS9IeHRITFFrYlZiZzFXWEJCS09mSXpNdkFvNnpaMEZN
        UHhnRVNSWWlMM1gycVhxNkxuUEl0MHdKODlIdmVrNFV2Ull1RVBDVmI0SFlhekpI
        Zm1ZUlFjc2N6M1h4Y1lkOUlKR1BvZFZGTkJObWZMbCtmU3RZMEtaamwrVjl2MldM
        NjBmMTJiK1hkd3phV1k4VjBYVGlzaXBoWDBQYk4zbEs5UU1vUzczOXNuVmFEVW1K
        UzNQN3lxd2Jwdk9EZFB3SlNvU0xmNUxoTDBWWWM3VER5N21SbkFjdGRSeFRxdUZB
        TUxOVmdpWGtWZXdwdG1jdWFza2tzVE5pY2JVNXBoWFdpcnMrejNOTEZVMEFPdmFK
        Q29QcnppMmNEZFFzdmVBK05wQW5qZ3RSN0NLSitHMGpqaktTVkltUmwwVUtvbE1T
        SmlDZ2ZvVUU2cGxqNUtIN2JGdGQvaTZFUW1lQ3NKdzBQUFVFNXBhVkxkRjlYRmtn
        c2RmQmJhT1B1UFBRcEhXaHdTd2h5SENoL3hMbElIYXAvM3dnL2tQMDJESCtmUzRZ
        LzMrbGlkL0dSRldXdUlXRTd5SmJkRnRGdVYwTVg3amJKRWdPVjdlSVJXSHoxM0RL
        UFY2OGdhc0pJWXhEYVZtTVFjeGRvbVh0R0NBazlnRS9QeGtPbGx3cUVLQWlZVWdx
        ZEg5WTFrcGIwRnMyRVE1UUxTL3ZmelNreDZxNnp4elhIdE9MUTNWMWpSKyt5M3U5
        SHB3NDdsd0duQVdmelFjYUd6c2lQRDhlVHVBVEJwNUhlaFZVUnFFbXhOeC9tbUU5
        K0JyU1NIRFY2NldUSjMxQWU0amZRWll4Yk9YcnY2bGdqdXdYN0IzWnlvSFV6NlpH
        V0QrZ1kvbGhXWFhDeWZiVHZJanp3OElPdzZ6OWd6d3FHUWpINzAyQ3F6TUZ2NjNL
        YkZONmVuZnI5SW1ER3lZOFJtbmxLcVVTSUhFMTFSVjJucjR0dzBoUUs4aytHaWUz
        NTdJakRRYWN5SnRaQVZZZWNKQWRVSWNMZzNnME1DcmVJUEZzeVdwRzVSS1NCeTY1
        ek41Q25lRWx4eGNSbEdZSjlDOVFqdzE5WHBMb043OFAzN2JoN3dSYmVEa05wdW9t
        cTRLMGE1cmVRYSs5MHprZWJzQ2MzNzV6czBwRi9qeDQ1M2RRNTc1QUt5UkdlMzJ4
        bHhSWVpydnZLcHZ1VlliZTR4OVRuOWtyZUdpSWNFOERDN1FlaDlNeVVPZHF2azVj
        WDhyN0ttcDIzVk5NSkR4dTM2aCsxQTBBZnppcC9JQzZzbWdHaHhXc09teHd3Tlox
        b0dhaEErWVpDczFJU1V5WHVEV29ia1dhSlA2UFFQZ3R0VVpKR1ZqeW1wNm1CSVFx
        ZU1xbncrSkIvSXFlZExMRzR2Z3FqZUJxd3U0TU5uU0hvbXo4R05LYi9CY2dPazNH
        UnBBclJ6VHNTbUd4STN1QUJrT2xTcVY0eG5DVUdGNUgzdnE3V1VlVE5wS3hXSlJ2
        UW04cnM0bGdJM3l0eVZqREFwR1hoTFdQNXdvQ0ZzaTVkaWhDNGN1Q25UV09uV2Ix
        b3F5V2M1MEtCaUQrVVJaZUYwMTZBYnlZNlZyanNGN211OW1WOEhzSE1YdDV2Q2hP
        elVHRFN2M3Vuc1JrVVpLYmE2QStvRUdUQ3ZvSmJjR254LzFHdG5BNnl4M29OUTRh
        VEZWOWQvZENpbitrTGtmVkFISWc2WitaOXBYYUxnQlQrQ3NLSGpGZklMcjRPMWlU
        Q3k4dGlFb1MzLzJCcFliNDNiWmMvQ28xckYxL0VRVEVORGQ4a05VSkRHYXBwdC9U
        OWtqQ3Q4Zm1LTnpFYm9OejlsZUd2b1NUa0MzaXEwbEpGLzVZenpPUVBtc3NFdwpL
        RlNFbHJ3ZEJKWVlxSlFKVkU5YVhvTlk0UC9HZjVxU0QyNElBTXBGajRNCi0tLSBy
        SWdvRm5Ncm5UcGYzS2J6bVFETE41d1NhZmcyeXg2bG1BYlREd3pUcUUwCj/9RbDx
        nRgrZHmtU9Lbe2gaSY5EKMpzt2kth9aWLpFh6VyA4Mv/uuC9ka+BOHpdT4rqziUX
        ZwhUkwJOsCHlmCs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T18:34:42Z"
  mac: ENC[AES256_GCM,data:9cskUhseJ79wh9atau+e72633GnYuE+VcDsF9+rt24eRNzmpTocFkbOpqf2oW0EsfWHm+n6VpwZTJZYFoC3YODchPxcIUwxmnv3/cXOHSMdNtk+zo9m6dBY+RXkaFi6Xn3Qlbtl6DEHV/LkXeICswGE+QTSozH6xyqkQIyNHtww=,iv:fTYyBpgFZn0ixxNy4yx2PCFeDWR4EfeAKWTZAx6haag=,tag:xzBU8nV0TRKg1gafiB0t+g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
