apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:bjtMjy4br0mXZkEXzpRul7HgSUEE6ZWBj6vshiOvi+AEQgFx5KcReXz8inwD3X+zZTues5SvvMBaxW4kGj8R5sgzKsxss5i+i7vMZIJ2udVPVd0YD3llYrQu9d3lwxY89OlHTBxxxPSNB+NZz6ofi0m/xxhpr/nP4XZjW2yuAm6bp0Rk7BEau/NvhEH+nos0OJUHG6slBGrcIeQdCvdyzFIyoEqx7I1Q5fF27CK2XTr8uV4R,iv:wbdDdHeYCldpGDAABAGNgx6ax3TxYB5Z/5J0b1/rj1I=,tag:qpyuorccsjTuREf+enen/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHpCcW5FYXUx
        cDVncWxuZGVKSjgvZVkvOUp2Y2pRL0ZOZjFEY2JaQWNRdWlqWHlHUnU4QmFXQlhm
        UHlsaC9TVmJmcUZCVkJhZWo0Kys4SUpUTzl5ZDBqaC9mVDJOTmV2N2NHMEYwdWw3
        MWRCWjRReUQ1QlpnRjBzS1FlNjJKa1ZjV1M3eWNZYW5ERXQxY3g3eVBaU0JKY0JY
        L0pOcGRCNVpNQkR3bEtqcU1PR3d5cEFSL2NlSTdjN3dKdkFPVkFJUmR1Y2ZLd0NV
        TjYvS1prNEJpMkhETG4rVC8rVDhUVTNWYUwzY1VuN0g3eGZIbVUySGhCVWZnd1ly
        eUNFb25NNURNQ0hGaDJKM0VZVDlOWjBCRml5RmJmKzA2eUY0Uldta1pRMks4SDlr
        SzBoTzFreVJ5TFhNOVlPbXBidnlqMzVMcmxPcFArd0k5dFBtYjRlcEx2RFZaRUxw
        NWU4dmdSYzZsUHZDTFlyZ21JYjN6VGppOEdEdnA3V1NNbXo4cklrOGpKc2VGWk0y
        ZVF2V0JsOVFUa0pXbS9mSFYzaVVnb05ielRHTktXNkszVjZSNzhwbXM2bCtyTFBX
        NG94NmtYUjNGZ3laQlp0NTd4d3RmelRFR0p0OVhEb0lzemwrQ2l5ZWlpUmpFc0Zm
        UHAxOUI1NVV6aVo4anc1Nk02MnJCejh4dHhEU29FVUVmWWI5V1l5TjhBVmw5U2ha
        NUN3Nm96d3lJTURRcGU2VzgyWjQ2dlNYd0hsUDNsbHMyVElrNldRdXE5aFlwR3dU
        QU44Nk1Jb1ROKzk0NUNCY3BYaWZ1U1FEMW9hRVVJSzhqYzI4WXpodVZBbmpmdUMr
        Y0xrY05MUnlOS0d5bjVlTksrT0VLajU5eFBnSGNjQVd0K3FvdHVQbzNRaENGYXlx
        OFUva1FEK3dvNW95U3FWMDZReXNoZTNrdWNwbThFTVIvNzNPa0YrV0p2bDd4U0g2
        aHJvZStsQ0ZDNUp5dWdMQlVzVmN2ZEcxOFAxcXBDZWlBSjNwTFFGZmIwY3cxc2Vn
        SVh6U2hvVzJmUjQ3UURmVWpzVHFyYzlYeWQzL21tWTZsNXoyS01FcWVMZys2YWdG
        SnRTNm9WRHF0V2QvYkFWR2pIa2gyY3Rvdk1DNDljUS9tSWQ3akZENDhrL2hPdXJP
        bG9MQjVIajJkQnhNb0hSdGdPa2NoWDA1ekIwb0FiTlVNZk4weGVKRlJIeEJ1UzhR
        c1RoVCtHVkEwQ3pwTFZPMy9jWklpWXpBblFHdCtpM3F2SEdTZlV1SmhDMVlKWG9m
        enh4TVpKd3BJeG5Xd3k4bHVvYUxXKy80bGtkZmZFRVB2QlBobzdFdE5EbW9LZDRs
        eGs5S3BQSmZTMHhiR1phZ1RDVlNNMCtrWFBWclRFU3djVjJ0bjRtTlBUVzRnYWNt
        WDhCTUhWT0o0ZGt2OWNoVy9wUU9WMUwzUVBoY3ptYXc0OWhna2d4OUh2ZVJBc0Nt
        SjZOZ09xdzZNQmIzcWIvSDNkTngrOGdtRUltTjFySzdwTGgvWTZrR0l3NWV0ZXdD
        RzB4VmUwNXBOZXVWVGl5NWF6bHcrUTlUWW9tY20vK3gyYzdMb0hEUW1TS2FhV1F1
        enUvR3NFbnA1eU5DRDdKTHhqaGs2U0puek05RVJhNXJRckZJeVJIM2tSQ3k4OG9P
        Q1Z3K2dpdU1keTNJbjQxZFFZbVRoT0xTZUprRzJ4UlIrdGF4VVZIU3c0QVM5V1Zr
        Z2tzdlorRy9rR2RwME0wR012dUo1TVJHa2dLSWlKc00yNm1jS0xZUDFpeHdsbzNu
        akFnSWVubklzSVN5UHdkaTVEc3pFNUpIemxQdzB3dnMyeVJmVHRHa1RvazBuUW5R
        aXhOMm52ckVXbk9tNXU5cGZocTJOd1MySTNFaTJZNTNGUDJObndOeHhjbzJZa2ty
        cFU3Ulk3eHMrV2JrS0pvZmUvdnA1YUM5SjJ6cGZ1SmFWUDNDQTY1dmdQVUVhZwpK
        UlpLZ1F1cWtjR0xOblZ1UGtQVTZOb0huRHRVMWV4QjZKamd3Q0xiQmgwCi0tLSBa
        clVtc3NYbFpZZ0FaaGZBVGo1VVFsRHdPUHVHWDRLbDYzL0NVaWVHV0NRCnTO89VW
        qygfKP7GBRoDfRyHwtD3Zqg2+5LFVVvCAKXvxpLoIm0G7h7ppbxmsLSOL68LumYL
        D9uukjLMhe+ET1s=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T19:55:33Z"
  mac: ENC[AES256_GCM,data:QrfqT28sVY0kqLfPsL1OBDisHCfyrOXtluhYYJXfa4xKRzSatTitZQ7pA1xcnq8KvMKhlVhB4yc+HHP4t93PCphFfWoT3iSFl/D1VosKH5BtsgG8J0lq84tEgozYmsGUbTlJ9i4WB4h3ov4KK3bzeKEDhzE8zEGgCHpY6mQQn2M=,iv:o7YzhAU65y/EmzVeGW3zpy5Y660E8px8xBCXHdrSqBc=,tag:1L0YZ/0VZroaoelJYQ4/gw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
