apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:KWzH5hK7DBiVP6qnMLL0wSq6KoxImd5CASmZjBMcgxviCL+0U7mZrw==,iv:2NvxBH6m0z0k0TSiGJzqCR9gV/sip6Ld/YD27yQRdAc=,tag:qVuXnuMILvrziZU7TRrQ/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGc5WEpySWdK
        eVVKL3hCWUZFRmJ6TDNyS1F1SWxQa2FxRVVzaUphV3FYVHdxQVpVQXJxWFU3b1ZG
        U0Q5TXhZRU1Nbk16OXBCdW5EUDBVWHI1VGpwNDY5YkRPcyt5TlBrNFluN1dBcTR5
        OTZ6SFpjbUZ5YjNrTE9mYlR1aGxjQjNHZy9SajJReDdmWFBxcDJ4a1BCMFhrYlR5
        eUxVTWVwQUlaUTVLL0VTS09TQjVxaWt1VGtmYittZXc1NTh4MkJFT2p4Z2FuMFVM
        RzRJQXNSRzhsSnNJWStwS0VCa05iN2lraGhLNGdOYmM5WFhoYVVFWEJuZ3pqcjI0
        TDJFcUVlQUMxUSs2N2xSY0VkLzd4YlZJRjVyK1hibDh0RFBRME9xOXRvR1AzbmFp
        UEtiSkEzenRzUHE0WGdlblFZQXlKYnVwUVpYZVBZUWdOZzhnNVd4bTFKZ2ZiSEp3
        OXh6cndnZzB2SG5uVENObkNTbnRRLzhmaTJyNEhLUWt3ZWpyUWJaK3lzRm9ob2NM
        RThSK25nVjRzU2ZzdlVpSW1zbnhYaVZ0cEFNbTJmOTZIT2huUjd5NWw2d1pZWS9m
        elp0Z21DSTlaWndLc2R3cXptaEtPVFZmMm9ySEVWYlV2c3NwK3pVQ2dpYzhBWUYy
        YWRoV1k3QjNqU0hhdmEyYzUvTW1pZG9Pbi9ka3B6MUpvSEs2NzgzaGVzNS82MS82
        bEJXcEpMUmE3cTN2b09yQjh3U000a0ttQi81M0Y3cVJrQlpNZU9UYmRBblJ5S0Rv
        NzFXYzcxNTNMYVA0YjBVTVdZU1ZvTFAvL1IwdkYwbWF0ZWlsMGZ4S01rZjJwZk81
        VW5qcnRXRy9uUkc2YlNvU0pTaWMwbDM1UWtDU3RySDZQVlVzeVJVWFVDL3l2UElv
        eEtMWS9OdlhnYXFKeXlscCtzOWlobHd2WFB1WmRGb21jSEt4RFNOOHE0REM5ODZa
        UFFQUkg1TU9ueTNINjBQUWRzNjdqTmt6ZlQvYVVsNmxjYlV4QkY1U2xLSW1SMDVQ
        S1lYZGp2U3lxNkFoTUNuaExOK3RhcWIrOXNoQi9JamR5UjdNWmxQMXdhdERkUzBL
        UjJENkwzbXBrWFNKOHdXQjZablFVZVorR09NQlBoNW96TjVxWDV6ek5hMDVvaUdo
        V2VBVmFWZG9zZkJtT0lmdzZZbXVQejVQNllNUmtGcm9takRCbUc5SFJIYmNBWXJT
        Z080cXZsc1o5TjNiZ21OWVFlYmFqUU9ucFQ0azNzM0ttU1lBUng1UENvK3JBam5K
        NW1JNG1KZDlsVTRsN0pzZUxReGNHYXE1M2kvQVd1TmlOZlpUQlZIUGd2MndvMFd6
        cm9LeUJibk9lbXNyalFQamhBQXZESk9yRWhDVzZxNjdobVBJQkJjRDNkUFlnamVT
        RkxxRDA1S1pobDF3N1RuYWhQVDRWODdiM0llK1pIbVNBSHJuZm0zaTBmd1lldmYw
        QmxvVTlHQzNmYUFkU0ZUTHZSTG1jdFN4bVA4dkRyZHBhL1BVV21EYUNldVB4UktF
        TGx3WTR3d1Bhc1oxQ2xxUFdBTGVSeXlBbVA1R2lxNlA0TUdWU3g2eDJ4cHZNSlow
        VnkyMlZmRGtidkFEOXV2YzZqYzFIN3lTTXJCZ29DMi9wUnY5ZUpkZW5Rem5IelJ6
        TnF4bHl3T2dFTWs2UHhpT1JJRXhqRFpOTytvWG9DUzVEUHhWbUJmRFhFODB4NlpI
        NmxERm14L0lxZ2N5K0krL3lMbG1xZ2FlK0l2Sy8xQ2M0NG9iRFRoWFVJQ0k5dndK
        TTNLK0ZtKzIvRWJtRXdEZlUwRUNQOVdvQ0NndGpsZnBpUmtEbktBYzY3OFZ3Ulo3
        WVFxRnFUNHNLdFVadk5pQ0tDL0t1ZVJnT05XUkwyYURkUHRzaFNTL1V2cVNOWWdS
        UDFzbFh6RVhUM0x6dDZrbnBqc0ZXNDFia096LzFrRDYwSXB5WEdDSzlDSmRJZwp5
        TzFyaGYzUU0wNXFZZ295Y2hRTnpYaFlDSFgyaGpRellZMTk3WTRJdDZFCi0tLSBF
        UXpaSUFxNUdHZzJhdDM1cmNvNjJLbCs1bXJGT0hLVDdHL1FSdnV4Q0F3Cv9gDRv4
        OIUBR/eV1zW39Aa6TraSl2Q426EuGb+68nVt7Xape9bHeYnenRt6E4PPvc2oBvbc
        Tp8LRCTz6YbFhBY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T19:11:59Z"
  mac: ENC[AES256_GCM,data:btvjJVNzoZNPyeTu25VzqpYflFUV/p01beT3buvC1ovBq6N+TAYWBJXa1r4rChXxVZcn4pTAs4ZQtpR6wbyclCr4H3HF/4GYf9E0sykVK0G+74Lw0FVJEVeM+r8SKBStTO7kYEjQoyHvgEeL2ss6PUr/6NjW/27i0/qxNwC9fio=,iv:Qd0MUVxODKAvNQo3VWILvqbQ/3vgy0UkVxIhbbTM3VY=,tag:y7iigejx9xozRdixNAHPcg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
