# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:arL2SNtuN0u5cWXUJkltcd+eKQHBK4hLVB8WjrBi0oKu5yUXWpLlGg==,iv:p7VhlzgZYaaBn6RvnvOFqeQ+fAyQ6o+22MgRLS3+X6w=,tag:H0j5vJ/7U78MJuZlyoPK0g==,type:str]
sops:
  age:
    - recipient: age1j822624yttmmve4h0ge5fu5ayekr7dcjwgnz73yspkdw8n2ax9eszyjs8d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTW5ORldnaThwUWlLNTZZ
        ZXM0VExkN24zUjNCa2xuL3I5eW9KY0Z6blNvClJERkRiVEJ2eWE4SzZKdnBvTnBq
        ZU5oV3Z3d1dDdXlsdElpK0VHbTJmdkEKLS0tIEV5S3dDcExQanpEeGpUR0p3ZGF4
        MkFoWlhwVzI2K29STi9WenJvL3VObncKrWE4QCsmeFFMC2D8ogPt6cxXr6vmjlGy
        3kkTYn8GRbKqhZy0HLMAAqM38XIhm3CazTf3NdbgV+MvP738CTaHnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-15T14:10:44Z"
  mac: ENC[AES256_GCM,data:AbHQUikRg83sYglcbZxnBLPNkBOwzEZpbJk8L5TyhU5d6GAVLOtlsPGH4+359mZ9ot3AS485gekw7FRTld+IYj/fKqoma0aAOAzQ8V7fRxv1APSb13++jhyhR/ckXZ9PCOCxpN+N8aCiYPdJfe1hkpIn5Kpl+sRq5Fln2J2LImE=,iv:a/WDPeRM9BEkEsUW4IdQ1pRXJ0nV5/2LSjSrw4vMlb4=,tag:Va0N5Ov7b5bVDNsJbJxYZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
