apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:cC6cQ/xgvbjJR/2RBDhg0MFZ53V/MfD10GMocqQFgHZ2CwB6+ErwaQ==,iv:Usk6z+8a7w26rSp59nH4Mq2OxxbJc6XnUyBZy5jYaaA=,tag:kF5y8q8VAzbHGaaI6CmbKQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFViV0wxQUVX
        eEpOTjBKWXJia2swWkh5Rlg1akQ5bW1JTFc3QjJ1ZmZ6NVZ4WTlGWWZRRW4yejZx
        TEYyUnZ6ZEhQeFRkUmZMcW1HbXRJTlRqV3NSWm91dUZDeUxqS2dxcmM5c1l1QkZS
        UTBmMThTL1lLRjJta1ZhUHM3Rlp2a3JIQW1VQk5ZNmdxQ3BOSmdSdEt0NmdjNFVX
        OGZmdUVwSVFmOUF5c2tnQ3lnSGN4STJhTFgyenRtc2tqYlFUdFNnSnhoQmFXVFFZ
        ZWIzY29HMWJadVg5NTc4SVgrRFNFbVRhR0d2eGx5ek1QUWJ3V2F6UDVJaUJaZ0lS
        SzdpUG9ZVVhoT2xxMkRGMTFTSGFuMFRucDRZakt4ZUVVSWJQbHBDaE5UZHprSzlU
        bW9NSXVQUTZaUmVFREczQnRmWTNzYlQ3YkdIMlF5QkFTc2hrVnBBdm03TDhRcUVR
        dWlxaGVkbkxnZE42V3JGczg4OTdoTTJRSFVDYmMyUTB0NDQrOGhud3BtZkJtK1Z5
        RzdEaWE0TVZFNGtSVVlhUUxWcVNUdzA2L3VuR0ZLb1dhZUNDSU0zZXhqbk9QL1k0
        VDFNN2JtcG5EWHdRV1k5d3dvRDVZN2VUejhraUJLbHcyM200aXNzaXladDI3VDNt
        c1JES0krREZSVWZHQStpcTY4QktqVUZVZ1JBMjlPb0ljVEdXaWRjWGhENmJOR1dJ
        eEdEMzNEOWoyNkd1bHBDTWlSd29zWms3V0I1d2F6bjNjblM1M3VESUJiaHZrZ0Uw
        dStFTlF3b2pZcldyVUtna0xZa3dMVmZkQU5hbHRUdUIvaWh5UFF3c0NxemEyVGEw
        Y285SUlRVVJPYjR5N1hidDJDM29XVDRDTFluOHc2YWlCOXkrVCsvdENSdFg5VTF5
        K2NjR0lvRTUvU1RHTUFqYXZkQU9ZVHhBaUllQUs4TGVyZWZkSkpma3ZEK3lDNExk
        K25mdjBUOTQvMHN6a0svY3NYYzRHaGdacjIxbzhBdERpUkhPWkpNbncvd3FmK2xJ
        N1ZjL1VGQTlKTlIvK2ZiSTd0QlovcWVTaVVESHNIdEkyRzdKSU00dURiN0lSRnhS
        dzZacTVBUGt1UFdPVFZ5UVlMOGJFVzlDeUxCMkRYR29PYllFbzFSc25vZEFHMUZY
        Ni9ocGpuZ1F0dS9md09UZ2U0d2U3NSt6cDc4dy9qTWFxd01sUFVDaDRsZk9ub1dC
        RGh4NVFiZkFaL1I1ZDVGcmFCa09qVzhCL2lVbXIrdkYzSzZ6bDFSdGxuZnMwWFF4
        ODNSUDhaa3gzcG42VmwwZ0tVTUZ5QzdKeWQvU2VVM21GL0lwVlVMN1FzRGk1T2ZS
        WEZJNk42dnF0dmZwSmo0SWY0b2ozVTIybFJkRXQyci8veFp6MEZyTi9WZ2lSWkgv
        K0hSMzNJL25yc09wNGRtNDFFV0hjOHdYdG1rakZXUlpTUmZKTW43YmJWTS9yakFu
        OTNCd1p3M0FUSVBxL1p4anc1Uks1WVZJYlJ1Ty90Zk5Nc2pyMXg3MmN6Z2ZKTWZm
        UzVNVy9lMENOeENGb1BmU3gxc2l4aXBwZVNPWTVYQTFHNUEyNnpvYXp4cElVVFdi
        UXQ5Wkx4bWVidDFDdnF1UitRMUlMRWl4R2RhTzFOc2ZxV2dwK3dOa0pWNHFhYVhv
        bnMrY3B2L3EzY0dUeE5NekpFaTl3T1BPYTlITUduVlJzV0ttMm1nY0J5c2tDY2Vn
        d3UwTHpqSk54eXRVb3J4MHQxdHlxQUw4NDdpc3pBMGlveEw0TEIwODVVZUJZTE1s
        dDBFNDRKSkpyS3R1Ujcxb3Vvd3VpcDJ4aHRmbU84R1NVSGJEWWdMbk9wRnJCU21O
        OG52cnBVN2NjTVhhcWZDbFFHb1ZPek52TFNici9XelFucU1Eb28rbWdveTRhbHRZ
        RDd6NElGWi9vdHJlMFp4Nmh0KzVzUk9MOU8rcEFPTnlMdjRrbFQ0cW1IQXBFQQpG
        TTNpMVZpYVFRZHdwTmQ5UzVoeWtSbHcwY3YrM0lPeUVLbktYQjRrbUtZCi0tLSBX
        NkhVNHZvVU9CNlJWQmZZQmNoSUc0MWh2M0lKR21BRUp2THJsTzY0eG84Cj5ZXiDw
        ea6TRXjU62GXS4JX08hBg6tyHZ547zM7/4dwk9xyu3w3E0nZQ3ebqWdW2+KjMgOk
        atKqsixeLKRgVUc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T19:55:33Z"
  mac: ENC[AES256_GCM,data:ski5CAiuX45Sq4oB2EClxek9VEmdum5cV4WwbLTF+r1qxPqtoWG63ZaEgYYV+5uZnRs5wB0qGLp7EBkTZFtoWMI6XmMcUL0ykb64orjIEBdZIZw0vCrB6yc9517DtBZt+acgkaRNPvLKCWe5ssPqgamszA8X7Vn09g7mvZyl5wI=,iv:oVMjXp3kPeTUwwvbO/8eeqmDKpdH+kNtu39UkgoQvXE=,tag:/7Y0SqEDJxlqahtaMOaRwA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
