apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2YzTuDU4JdZ3FQnq+pwM1oZmAil9yXpC/0k7ZB7rqaEtAID2vNYKnw==,iv:w1gK4Y9ka8kvH9fUn0JAgwumOyTlGyLILnZczJ5rJq8=,tag:113Tyfu0/02oPhfP1Ng0Hg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFV4Wkp5ZS9m
        U0J0QUpYc3R3QjdXZkxaeFcxUE5ZTGllcmNiRFhXQ2xxYXlqME52MnZuNlhMUWd1
        V1FPU1hicEw5OWl0SzZ1Tmo0NGpYNmxqZys4OXlsTVg2Qy9EUlBlMm1vc2hhWEdZ
        MlpEem5MaVAvTlRSaTVoYlkrQkJVaUJGK2hoVVVEcGdsVmdhVGZYRE9ZcUY5Uk9R
        cEJhTFRoMFBnUzRqLzBwREE4WU9uNzJRc1FYcTJneUVyNFQ5RVVhVWNOSmJUOStR
        dVBFNlRPeGh2TG9NMmlFK1lTc01qWmhzcDA1dE5WVzhSRlV1MGozVE95eHlyN0V1
        MUNaNytCVXkxQlFVU1RvN0o0WStnajNJc29DKzVsREFCc2lvemd4NE1ZOFVzNFZj
        am9NQmRCU2JORmkxQVFod09GVTBhRW1MenRCMlJpZ0pRK0IvVGdRakFaQnhUMkpV
        RE5MOWU4a1A3ZzFCWDlrQU91R1hiYzc1WFoydmN1ZGI1L3g0bkNSTk9aeGJvVHJJ
        Y0FvUjBBRjU5NWNYSDQ4d20rSktrRGtDMUFTMkVqM1RSMy9wbVp4a1JROXZuQ2Jw
        TzVkTlpQaE1zampMN09zVTZ5R3pOWTdMTkJ2N1VBay84R0k3R3Z0TzVnVkRXWFN1
        c0ZRYjF1UHljMTFVK21QRFdIa29UQnNjQ0QzdzZpaVRyQ3pJNndCOHlKVHoxeW1y
        M1hod2JwZlJ5RUdzL1hBR2gvenlyQWx0RVowR2w0NVlaNDF0Z1NvQkNGdlkvOVo5
        NGJSVldBZnl3Y3RKVnIrVm5CbVlwOGtzNmQ4Ujg5dzRTWEkwUlJOaXJoZkJ6K08y
        WUxWbHhQb1RPdWwyYjdKVHlQSkFDa2V4VUlKZWlyT2FPaThQdUJGb3VlbXFZcnFG
        R0VvMG00ck9ib0o5SXozK2ExWWlJRUg1QzZ4UWlKcGhrd2hGcEZWZGt0Y0M2ZERv
        aUxDV0xNanhDTUlnNm8vQUlDZklPQU1ZNGRvQU9Hd3NoSDFnU0x4OCs5RUhBNDZK
        OEt2S0c4czAwdE14ZlNDY2hrOW0zR2ltaTV2Q3FsMmYveit0QUJtTDNMa3RoUVlD
        ejdGRDVnWFUzbmpYQm1lcy9zUlNVWjRYQytYVmdUdjdtSzQ5YTdrakpyQWl5S3FV
        R1hWNDhKbzJFcTJ0UTZEYVBKeWJ3aFh3djQraFZBTGZ3MGNld3V4MWpJMXhmY3o0
        d1ZMSjNkVzV4ZFNtTXpVQ0gvVG1yTGQ1REFkYjRCT1Erc200bjFRbDlUazg1bnA5
        eHRPSVpVYSt5MjU1bVpWbFJLZmJ6TGprTWlmR0crdXFoQ0RKS0tsbkVtWDJ4YWFp
        QW1idkg5VXVKOStQSFNWa1BOeHZxKzgxeXJBVXZWNmR6UGxHVlBkSXU3bXhnRWVR
        QllnVUdocGdUVXExRW9FeFg0K1hBK3p3UzgybmJOY1VlU2xqS1FCUnhxb08za0t0
        eTlYUDQ0Z0U1Vi9OV2lzZncwQWVpcEgzaDdSMUZVYWFJT0ZvQThlNlBrU2lmNzBu
        TVp4K20yaTZDZmMvSSt1eEl2ZjZWTEE4ZXF5ZndVb0YyWFZpeHdaK3l2dXh6Y2lV
        NXFHSzVITE1Nc2h3dFQ4MjZVQkk3V1JIREtIMHNsQUUrMzdYVEgxOE52dVZwQVlF
        RkVOYzZsMXhUUDNvMjhjNVUrYjhuZjRQY3NZOW9XbEY4TmdyZTVkTVl4a1dXdlhB
        OXZocjdyeitua1BRN2RCcXdURGV5Ti9aVW9NZnljbkZuWHZ5MER5TjVuUnJ5dis2
        QmYrUjJ6aEx5OFBOcHYwRDRyM1hyZmh5VG9ycGZiNmlEbXh6QnFJc01uZ0pyS2lj
        ZXhMOE4rb3hUU3N5NWFxWHRobklkWHVYenRtMG0zNWJzK3F1UTlqQTJpUlg5V0R4
        WU9hNWw1UFNQbXlDU2ZOQTFTYVZTeGlIMC9XUXgvWDY2YVA4b1ZDMk5YWEJidwpF
        c1lIOWJmQ0V5M3U4VzN5N2pqNHFPNkJlVGZHc2dsdGdVaGdUZ2RSWEVBCi0tLSBV
        ZnFHaFpqUFEvdUtpOFRHdUNJZlZOOEYveUwwQldGUWlkQzBQclYvNXMwCh8yfMDN
        VbQ85iR7cheAemWUBAoCSg0uilx2Ul4ASzH6LZ48RtZ/WfiAIKCDL06EzHTN+f4J
        1txf2ZIfnOO3pJs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ztkqwxg42qtgsk7v27tm7pnfd5jzwmk4c72nr9kyxp7zfz5v65s2l46chlezww3v3zdyrvj9yqs22xaeqdnvvqeugyv2nssats6gwlaxy3wng9ahfxlwl4tj2s46y2puhs56ntjh2ed9rynhjlg4cfphsssldplak2anlyr5uve90kvgequn572q67mlk5qv0jgt0cgkklgmc4fl6keyr6ygpdcx62hp8crkqqpl7ut0754nwdtrrt6msc6mc6ufaquu4xejpzxpy9lqyw0evjs5yvrz4tr5hy4cl0jssry6hv4hmpmy8xxgju2f5apyn8x4wsntzapunvsdnxrs0jw43tzpz9ujsedtuvsqd5q3247zp3dc28d7gf3kkpvyg278h9lpd7g9r37ay3jvq9qlhu5r084jr09x0j7q7600ae566lw292j408fzyl8hz3fffftmtv6q8uc24nvlxqetd0rnrq2sspsnxjfpt2epsmhv3ss757aghf23rd0s9w695nk7jpkykefp97m5uvlcg9cp3nq4s2z57y4usgzqecnu20qettsa6cv935kxqzq3wdzceqsyh97vkx4und4llm9s54h5nhjzhs9jqcnkp7djshqc0h8ffmxlcr9atgmn0s9sweanjxcxkffust3lfdkhkarzs72sa9yu0r3njvytqda6qtyf2gj49dg6d5e6xuls74fvx3274fry5d3ygqzskar9mfz3w969ntax4hc8vku9ce0hc69e8qy7cpymg72sev722q3dx6k37zcu479rdmcct8mn3zfmcnxxc5frw3n8mrdcylztzz9e759cqfufjmfvhfezkpfq339sjzxwpjd5crtc5q8ptu9l2xs9n298pzvg63rva5n6p722drl83255tec728pp6ap89qg30xx8uzfdxxew0rm4wc5tj2wxx2f9k9d0ejaqkmk24pfk930ywxcenfqzgexx783xyqu5jj0tpvm5z2njw29daatrhs0tx0jl9y37cjjlk2davzvfe9pmcnuqrt3y99578jmqqft4mydrw8fjrwyx0fe3m3jpwdyvfzvfw3y4rw2w0g3waasjrvtqm049w645y50c5qp6l7sk8hn6wak6jemv5d8a9dv86crtk4arxcvh8ge4w33qpyrkfdnjmzprxdaqfcyjwmzrdp0zs3f5rv4y39q8et7qysl90r9v0s4ghtarj9c84x2txgj8xh8avq4f97xrrjlexky2xds4wzklpfzxq3ache08zm9xsq3x24dua969dqvrmn8jwa2myaq00ff04z222srhuvducqttsh2tedz0lg5na55mus56snx4zjtye2279zgqhkyp2tcftfej3w4m8v8x8xfcsvfk3dfesf49gupp9qw0kc4fx9fj9783353sy29v62kq8f35fkpf7fzuhv46fd9d5zxfkksmfqt39wwzp7krtddxay6t9gf2xa355afzqwfe9gv753m3vwpw70qxe5cjnnhqym28jgvtpv6jtpd323538jznnfgw6fjznsgz4f24ydn4rshg93js7fdkpkfuj26cr6a6ydz2ffwnqpupgu9ywm282m9559k6p9fs4fscsgz7ddtycnex2tuv3ga90xpr2ynhglrezff29els905m9vrmmhqy7drfpuyscn0ckrg88r9ekd9l35y657gcts6652wk792zsgv5tgcka7gr3srvjjh3xhqdahyvcfaz4an3t3rmqa20z3dtexqs7cm8r47njuw7rrtcy7hxqp6y2jnyrchr0whmv6vyx2gssaays3cxzmrnnfk8yaw3v37lynw66ea7ph2c2xelg8mvw0upd22930jzwex2tkfcdfu2z03damxcpyryvuejj8mw4p03vjwlcqar09spvywksaug374n2rf4lzn6wqjtglr2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T18:34:42Z"
  mac: ENC[AES256_GCM,data:nUeIR+JHzZwO9BLL7rND7whz1lkdVaafpOayfl4t+jx4hfqubPoti1g622ykMRNkIXtLz6rV7LSjhJkDHOuo1HDB96PyRLOYe2T/JBUsaHLHBOktfNq9bsCd8DYBOD34GAvb4oRGF3Hm997FzApzgdHiX54g6oGk1Yc/cTS3NIk=,iv:Tg4iHcMzRciOEAjQM6dkMEGdtM1dhn1UwWZSK2Yo5fo=,tag:VEqzXeOtwBi8pf+bem82zg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
