apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LfNIqWuK,iv:o7LCi4fsE2HxG199sOsUBKDVEdH6S0pBXoBw5HB4XC4=,tag:ozvxYHt0V4wF8qlV8toXQg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Ztn4UAe4awOlzExuwUSD+oWbH+aVkAaT4Q==,iv:CHmwQcQDSmQ6hIUKcjDBlHrQ/c1Con5bdOnvSKGeLMs=,tag:qaqUDruFK90Glw3+lVd1Og==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:g6J6JEvlr/xHj4p6uQh2vnyNWpYAMUKuqJTDrVfZHxmeTlID,iv:mY1p88I6fPMGqPYsWkRiMEcTytYOnFgB16eu5p3LBXQ=,tag:BrVXe5uiyMs2+TcczavCcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2hoalFqVVRoY1lLWXEy
            YzJiT1BJbXNlbm1TWXA2S3B6MHpOZDFXOUZNClBTVzlmTVNHVzJ5ajltSUo1Q0F3
            a2FWTit6NklieVZKTzJBYUNVYkpTTGsKLS0tIGFqSkJZRjZyMHFOSGs4UGJPVlZS
            MjBmaUxNSFNJcmdiTHNXdTRnKzM2RGcKqRAmRajmJLgoFFc8Mb5e1vGVqPNJ9U+r
            w0Zl6M6+7N9rqX6ghPbgxBh+4bj3uwW6JyTZe/p6Wcd0pEulE6hYtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T20:13:55Z"
    mac: ENC[AES256_GCM,data:0NA+DN1SRVKEw15SJ5iJYOqI22p/a1WWgUNqUiqz1af9PH0zhRtZvasgIQDGaoyitZk7133BCBJhtM7ZsC0OAH1lulOhT5oj3w7+mSH1N6Hp0+tAtvcZ300oAHLyGxg4RNvRP2STsuxyZSdJEkoMfCeyTiSR9BO9lf0dgqHaIlw=,iv:n/GD7jUwEJxHuwwYfnsKOHSXvxO/5+l+vtff6YFmRUY=,tag:SSsTHwMgmEcsnuzoDXfyJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
