apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZW7IpKEg,iv:cas5uzWfSLCWITShxEsDUDjtVGFq/iVXrPT8c92gD0o=,tag:oj7XLxZK1L26fo8npNm7Sw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:zCygSmZGQkc6U7qVB2X1tqMnbIciYvktwQ==,iv:/8fHMybcDc7OSRl7tNGgoNeZ3bP1iFNfLcJYROcr59s=,tag:P0wh/SVw6hue4v/GtYOiIA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:e5JM6aVTSGMNqGUgVjKZb957I1DhkRcBBLV/koFcFZSB4lTY,iv:i2f1Zxouo6tguWYrpsessTecg+BSY7IbJlNbvVXtjz4=,tag:37rqEIs40aKU6qhWjrnJDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ0RlclVqQXc2dWNzSUcv
            WnBod1o0MThReGM0N0hTMzUxcDd1S3MzQlh3CitqTnhIMXpuTWhzbTNwZU9Mdlpm
            dmNkV3dkMjdGTmlLeU5Id0Ztd3c5SjgKLS0tIDQybUZHQkJpeUQ5M1RNTmZxbEow
            aUN1Y1J5RXgzLzVRbUxjL1F2bDFtclUKtE12/a+XjAFsFh0TfwnVvZ+5VBtetKZs
            I4pJN+FgQ4+UgLUG1XjP1jq9WhDkzMCPC66fNTsFpeSRvrXrGVmQ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T19:42:52Z"
    mac: ENC[AES256_GCM,data:GDpNqm8aC8gZwzTX5ksyea1JvxHUX4aJXrYjLnDvAP8PGdJ7JRgUOSFcaqlQO5oQGO+cNuOfZwF6Lg61bIXxZL4zwcoJIbrYRgJOkfuo0/RYpGYPKAEjyDLhRO5T2iX9RWGBVReYIgvtG4Bvw5n6NTEz4T9p5gCu7NqWj1LvOMs=,iv:41Seb9YaXTNSAy1k1+6yrl9fJbKZ/W32z4YtZi1mctQ=,tag:9OU1b6QzZcRk72brMDNcjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
