apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:rbIJJtZY,iv:IOzjN5L9qpAzrfIuRQ2VUkcg4znojFt1zjt3kBVwLu4=,tag:3twph3AE14CXYxIFZsD9zg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:S+jgHBD+MZSN7IdlB6PZbwXna7tzMuoO+Q==,iv:XGo+XZBLrYGErG4tpZt/Ni307X6bVsWCvPgR6Yqq8kI=,tag:SL32FDzmN/mCQ3QpgSWXog==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KRFuZL7K6Ax1ILEJC6CLhgSq6nKn07c1o3rlnyRyWAPxqdfH,iv:oqVcSedcmIN3fYSMaegv5IJA+q3G4VKyY2qNK0ruTUM=,tag:k80QBlG/vKzKnpDf58yELg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVFdsVXpLUDNWd3NGOUpu
            VVA5WnFyNk9ENUN5MDljbGl5Nkx3b1FzUWdzCjV0K1RwbmpJcnJqZlVWejNPL3RH
            WGhBYjJabGV0UEpybFJ4VVpiU2ZyeDAKLS0tIG8zSTk5ejhJZGdlck1sL0lNdXBL
            RmJ4bHVXNUgzaVFQMDhWWjRxREE0ZkEKJsEZn8ozTruuMs796HOgfM/zkIR86LnE
            oo0ksF1uyOxLon6KZn+s3xd4TzwuTzP+USzSebqae4D7lgjcOuSndQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T19:45:23Z"
    mac: ENC[AES256_GCM,data:GPxJUlOCC5Az2H1szALYB23KVMeo0bnNizzgY8pJ1FtiQ5RJ9FIdhteYs5PzmVJjWPSLqlF7WXNvM4x0clDfV+AdwbrjLuOWtzGvm73sb4qp7sSQVDeb29WciEqrwv0Xu0kNcnbkbootiCzFcqexdMzhwkWz99B/L6OXEL3ViEE=,iv:I7mMlPvU3+qmHEbASw67tZNS8P/zTDDKo7D/zulIBl8=,tag:I7Iien3Z4oY3WFv6AL6F1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
