apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:JKkg9SXA0YHPtpoOwnipJTBKZC5UqSlBN/GkN+cDWvF7v7Y4FbCnvMGKX2RdUTQ4hLAol8UneLnWe63/5wW3xxLtcCnCQHEufD6fFAfVwoGWAyCgbWZyB6N6RU/p6NKD44U/XziTur8yroRSenD5NH4Zv3lMexsA1bGnMEPMRv0w+NW9s/V7qnvJPIPvJIPOWr4k1YFglkfgogM2e8tc45sBSH1n45RboV+Ww5K/1n8ntGhWnJ7SzxQruSWgy0S0az4t3YR9sL+8mCoXAD/hOJtMks4n4r8vqi//NQdiQhRZ2lflnUTMKIye11kd43Ch0zaF8stmOA==,iv:D79a6wtEk5Y2oiWMNQnIfuLuAWT069sV/7lGK+1HC+Q=,tag:0dA0J4RaKiBvDDBAeS5gTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWkNXNkk5c1hEQzJCTFRi
            UnBqeEhjR3U5MWkxNnVHVE9TU0x0MTVadUNvCkxuamNOZGFtdm05WU9CdnhyNTV3
            b2JGOWtmNWhWdWkybGIzTHU2Zjd1Nk0KLS0tIFk5a0tpN0VNL1hBUlczYlVWN2N1
            SmNZUWVoeXl1NUo5ZW9SQTR3d212Sk0KdhoM60kUkXrIrDaGiVj7MWkR34srDczK
            bAD+0g/tlmKCOSFEsdYP1goTAjUlh0VFDzrA2hXHDRqROjeCyCenzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T00:53:05Z"
    mac: ENC[AES256_GCM,data:2vgN5EoBWI6sPWk3Cqh8uQOGxTp40wqFqmxvhlDvqKXsRCa1ATPQNNlA8QUszXq7E/vEoOUTDSUjIGYEaQADUbsEs+/iSXWFePhX3fui1kNNXo++Yb/kaydAUWojdf1fsTvBaOECtkIvBsS7YSF6BLMHiX53qKumLn/DX91hURQ=,iv:tO6O2+8QUTBtaqbnn3RPpH8bOHQUlgNuPOtpJtwUNTo=,tag:DsmqQ75q5g34EIT+CcoJrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ2Jvc2dXTnB1NFMrQWtP
            eU9lWlZjdzFqVS9vM2Juekk0SjZiUTZxUENFCnd6MnpjT1ZCN0tPeUNDdTNRcmpW
            N21SeGxucEJYYXI4ck9rS3ByWllBQTAKLS0tIElFZzJOblVhbGIyWjNETWZQeC9F
            dTJqTDIyZW0vWlgzbVI1bFVReHJJelkK4qHf3OLocars+Ev7z/yvYl5LdueGoGm6
            B5vky88uIlr1BLHwTnDochTE1eWwGCDALH3F4BEswE3LrJ0SJpGglg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T00:53:14Z"
    mac: ENC[AES256_GCM,data:EZy31JhZRIkrnzuR+LLpI7AVtLr06oH6+7s1X0848cTYylUsD43lYMIOzlFUDM6Rx+U4OmA0rUM2SicRF8Emt2Klm6dykgM4tkZ44ij7TlW8UmebAI5EvsoqnnraZyRZR0jWMdRhl7HQJNP8CrGVZsF/2WsZACyaH9e/GXyBo4g=,iv:UQalOQJNHZ8UJtYW86UW5nc4KSAefHNVDRwMdDuwLw0=,tag:rdQvto/0dZ8nSc01xCIsag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
