apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:xQ9K259QXhUbYkjseEb8mibSYuMF+AnPQupGZgnTSOiKMvMmPbNB9Pj0ozYTf8rlcdZJKbtFxJU0jiqcep/q3irveg6IQngGOBHYi61QmWXj7cRTcQghuTvlfZ4AmhSEoZEBRktt4swMSnlIjvLad0EngXUXYP5Pu/J2umlMYOHpKTijMWLKf1675cY=,iv:LyirDK3dAdV/42l7icZUJ4PliObfgL1OfZPis8CENPA=,tag:juOv364dSuvaWEVBL5bWGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ2Jvc2dXTnB1NFMrQWtP
            eU9lWlZjdzFqVS9vM2Juekk0SjZiUTZxUENFCnd6MnpjT1ZCN0tPeUNDdTNRcmpW
            N21SeGxucEJYYXI4ck9rS3ByWllBQTAKLS0tIElFZzJOblVhbGIyWjNETWZQeC9F
            dTJqTDIyZW0vWlgzbVI1bFVReHJJelkK4qHf3OLocars+Ev7z/yvYl5LdueGoGm6
            B5vky88uIlr1BLHwTnDochTE1eWwGCDALH3F4BEswE3LrJ0SJpGglg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-08T22:29:34Z"
    mac: ENC[AES256_GCM,data:XxLLJOz0RXxnGnn+DcQkKQkPzrl4VYvQuNevvSp29QPmoPLg9f+kCSpv2P6PKtr3/XNfFdn0cQU1K0zz+2l49NGEM3uTTSznlELnGy2G+96V9Afl6cPG3PXV2LifHb1dMLdW8MAJtexZhrW1aMxpceMboZsacOxcyvALXNmwE/I=,iv:PJ+lwVeKHmuKrsvksIBgdtqHVo0Q7tFjWWyvIp3b9RA=,tag:b3eLheiJKOaw7oWLAsTLHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
