apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:q8irZ1zFat+bizO4q+sYLNsOhpyECxKptVmhSJt6nEQkB7mbF/5tYg7v7L0XtT/JjIexKTw4cOlhnmF9BAMHGm4+rjZ7B2eAVZb0wACRuOcbA1+w11DyY5xLuw1J11PBIlrGYG2Z2Ej2liVnp4oxugQy+BaANQVk0FV9kDdLcfO3UIX7,iv:uEWLh7uaz2ybQcFJQa+mLsBSc9dVJ7AWNYZgV8XvpB8=,tag:iA+zbsK43wfXmIyFEpqwSw==,type:str]

sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ2Jvc2dXTnB1NFMrQWtP
            eU9lWlZjdzFqVS9vM2Juekk0SjZiUTZxUENFCnd6MnpjT1ZCN0tPeUNDdTNRcmpW
            N21SeGxucEJYYXI4ck9rS3ByWllBQTAKLS0tIElFZzJOblVhbGIyWjNETWZQeC9F
            dTJqTDIyZW0vWlgzbVI1bFVReHJJelkK4qHf3OLocars+Ev7z/yvYl5LdueGoGm6
            B5vky88uIlr1BLHwTnDochTE1eWwGCDALH3F4BEswE3LrJ0SJpGglg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T19:11:44Z"
    mac: ENC[AES256_GCM,data:PwK+EKwQ0v910tyQjSxPwWkeeRAdUdyaoYaUobDZccqC6a/ZA2WQu1oYTLmJ/b5cuZdeP9zmxexOi+a0SMsPIo+t90sFTdqk1wl1txbfMd8A3+ilP3fFa7C3wvLlIAJklN7Cm06G7JJmpTJLBC2Lvc4+lphG1yb+hkDAioaphkU=,iv:14wxuyW6vLn/07EwWhmtN1tHKMgQl7/qMXUY+J51rTg=,tag:+FFgmHalvprYdZ54Uz0lvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
