---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager
  - ./default
  - ./external-secrets
  - ./flux-system
  - ./kube-system
  - ./network
  - ./security