apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:y2eubY8UoTOrp4H+hUHK9T49A0zUfvDT6hVgzqUxpqk=,iv:FFdt2mK0d7Mb54vzkiWH29CgliDpFW0Faes8vlUT8uQ=,tag:Zw7L2cuw7aX18a2ewG1LFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMUxwaENJZkZaU1hWUk5X
            Rk9xbitkdGpwaXlIbXdmNEFxQ2tFaFhnOXlnCkFNUDFqc1BYVUpJamJNSVJoSXJE
            YnFxTEJMaWFmRDBKekpXclZobmRFcjQKLS0tIEZFZWNhSi9jay9rUUw4U3pjWUhp
            SnFLSVVDMDZKUVJwMzMzSmtZM1N5cHMKp41NZAJUa9gdqBShVgdUERMTyOlPstbz
            /rLafp/s9yorN02t0uVgC659rpeGwKX2NpofQ7d+7250KjU5oReESA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T19:45:23Z"
    mac: ENC[AES256_GCM,data:UQqOXEIF6j89XVkUbgg2A5WDI+GgoCKdZWFUcmDh0PPP0NEoIgplSTqsUD5JeQacbBrjdj+20Lna84npvde23C2z0YDhDkL5dwsA5Qvqr57SeDQXeUCkmzSpm9lq1uVmFMep8Un5v2sRnzXUp/nwTKYjNEDI8uf9doQHmS5opBo=,iv:qHiNP8FDXfTuNqi8FmDId+TpLcuK2mpppuMCSvtOdiI=,tag:8WFHRtHhVJc3bq+3qH9Qgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
