apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:MxZTh9RupwbH5+kxh0Og/1Z9aA1rsdpL4ZG0KTSnJ4g=,iv:3EONEqSaKDMFVMCzK7VEhwLEwBB+QhIwrTJE1V8NG/0=,tag:bAR3k7k1Uxgb9ZOFk8Adiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWkhTVmtlM3RFMHYrSk5k
            d2c2Z2hKek9rODNDT3Q2T3UrWHo2VkxIQ3d3CkMrZGpHSWVOdGd1UE9JOFFvM2JX
            Mmw3bW5pWFp5ZDV0SDFQNGJ5Sm5UK3MKLS0tIE1jQlBaeEIzcFN6dXlMUnhGdFBQ
            QkwyNlpITDFTcXVZeHMyU1Q4Y2ZRMkkKeGYJhgGV9xLqtYrL0AMxG1nR7Gtqe8oT
            SB3oJ2X5n3t9GdwUu3bMMuUi+yhQQndzDhHYaONJIuGM2G/WAvrrSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T19:42:51Z"
    mac: ENC[AES256_GCM,data:laH4bjpK+3J8mSkMxoErEqJifBYvik8YzI9UvFIB3KBF/m0e4yzBxfa7CZ6mhNZnLgcL3ywLp32eTwz2jJAbbZJbgTQ/I15JhL/uJo9s1bDwi6FOqKRsbeAwINWcfMtNCNsqrYdr7OqIyNXP6wj7Z3rHAgmA6JJ49LcvE1YuhpM=,iv:NeREv+XAK2ykTtU9Qjtt1LEUJnfZZSVekOJk+9Bjlq4=,tag:wJ1ZOg0+iUh0dLJF7K1ZDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
