apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:NcX+7yE2MB7iz17y4QQqcxsfg4uxzNhph7wBLAf7AE4=,iv:Z3hhzoNuX5NABt/18Ge3YvHpu+hy14Xq4x0Xdd8rBWM=,tag:TiEGHMvUDDXvXyOzJ6xdWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OTRSSldlVGxwTXN2WC9a
            OXNRWCtzUE5sQ1B6eklKbGlLMGkzUHd6a1Z3CnVUOHlFT3Q4YnBLV2pXdC9WS3pt
            WXk1TlEwZFdKYjFJNS9oa0s5UW5qbEUKLS0tIFVQS3NRR3dNNmJiLzh1aGlyWVRq
            bXFNWlZaM3FXOGZDYVk4dzh2R0F6MUkKkvE1jtESmxW2gfL7kOZlpvgKeWdUq19G
            fpTG8Zv20SgxgKHIoUEjJ/TgjPv+tzMLul+wcqnb9NW2G+4379qdIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T20:13:54Z"
    mac: ENC[AES256_GCM,data:FBUvlJMO3jWUIi/iuoxyARuwV5Tes2/wp+p0Tf5EIHZV2HJ72YpV3YY4eBlCCkhp4gb2LFwrhhye6VXBDCDqMgBTzT7F7c5H8CmWQruqBdFulkEi9+WAgTDSiwGHh/9b1NJeqpcFcRJW5cPbQA1EC4lKzZLxCH7x2ZLx38NWdwg=,iv:txfQgrJDyotLeucAUdOLXvaTlTJRgdSLXS9pCWQmMkY=,tag:GwZkOE8aa7CS0cyMS7GFkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
