---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    template:
      type: Opaque
      data:
        # Basic configuration
        HASS_HTTP_TRUSTED_PROXY_1: "10.42.0.0/16"
        HASS_HTTP_TRUSTED_PROXY_2: "192.168.1.0/24"
        HASS_HTTP_USE_X_FORWARDED_FOR: "true"
        # Add your specific secrets here as needed
        # Example: HASS_API_PASSWORD: "{{ .api_password }}"
  data: []
  # Add secret references here when you have external secrets configured
  # Example:
  # - secretKey: api_password
  #   remoteRef:
  #     key: home-assistant
  #     property: api_password