---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    template:
      type: Opaque
      data:
        # Basic configuration
        HASS_HTTP_TRUSTED_PROXY_1: "10.42.0.0/16"
        HASS_HTTP_TRUSTED_PROXY_2: "10.0.0.0/24"
        HASS_HTTP_USE_X_FORWARDED_FOR: "true"
        # 1Password secrets
        HASS_API_TOKEN: "{{ .api_token | default \"\" }}"
        HASS_SECRET_KEY: "{{ .secret_key | default \"\" }}"
        HASS_LATITUDE: "{{ .latitude | default \"0\" }}"
        HASS_LONGITUDE: "{{ .longitude | default \"0\" }}"
        HASS_ELEVATION: "{{ .elevation | default \"0\" }}"
  data:
    # Reference secrets from 1Password vault
    - secretKey: api_token
      remoteRef:
        key: home-assistant
        property: api_token
    - secretKey: secret_key
      remoteRef:
        key: home-assistant
        property: secret_key
    - secretKey: latitude
      remoteRef:
        key: home-assistant
        property: latitude
    - secretKey: longitude
      remoteRef:
        key: home-assistant
        property: longitude
    - secretKey: elevation
      remoteRef:
        key: home-assistant
        property: elevation