---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zigbee2mqtt-authentik-blueprint
spec:
  # See kubernetes/apps/media/sonarr/authentik/ks.yaml for why this targets
  # `security` rather than this namespace.
  interval: 1h
  path: ./kubernetes/apps/home-automation/zigbee2mqtt/authentik/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: security
  wait: true
