apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:fNo+0GZz,iv:Qovm1QKP8XSQ5bxwOp0Pj/jIMUPRRBZ86jMCyGltnVc=,tag:GZPCn4RjJ7g/VSimYIIv0w==,type:str]
sops:
  age:
    - recipient: age1j822624yttmmve4h0ge5fu5ayekr7dcjwgnz73yspkdw8n2ax9eszyjs8d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZllTRmkxRkJ3cnpCbmtt
        MW5LbWFObTNreEh6dmVRMHkxWGFoZGkxVzBZCmlHUzQwNG5GbmwzY2Z3Nnozd1lz
        amVjdklKYUc1cFA3VmtsZWJneHdraEkKLS0tIFd0cUxwMUZ6aVJZWHNsL0JVQmdu
        VlFqU0tHRUI1aU9scGFMQkxnTHFKaUUKHgcJr9s0/i+74qgh074XqHZmle/7xChZ
        /+iiZYeUiXPOaulEaqDmfq61Z0cCT8scFDfV4ji1wWHhyEGQa0mVGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-19T08:06:13Z"
  mac: ENC[AES256_GCM,data:g2XPNjFfYHhIfu1WDnGAAw7FQ0Q3+C0Qtmc7BbE1v2+EGEDc6S9s6wKvlj3Fmhw5/2SEFUHUa/6WO95byTn/I4VxwYj35MRXolBwqSEvGZ0v/ITTBQ8m8/6HaGFkcBCI1qnNnCafhJn5jMW8HhNodbEMyTRw4TpsmAibENrYLyg=,iv:aA63KZtNuQ3EYvlRZdSzTi7CKfca505pdtHtXXmvu18=,tag:hxGcZD2+MTlB6vD5lmCrsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
