apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:miD+oQz0Iqdm9sccWNbFpJ6kXKMiY/4cOlls5cBbmhYhLQGVlNw4JA==,iv:c283cTqy3aiqg+WapsgUj/0/7OyHy8IKPi+lN40f4iE=,tag:BSTBpE+Qq3YGCEbyXmyv+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvR293MjJaUXExTlM1V09U
            SHlrUWRhSlI0Vm1iY1hEcEc0WHVEOUFXakRFCkVVWGpBZTdYSkdHT3pjdTJ0ajhC
            ZzVMSTNIY1pyVjBCcGFtZGcybG10cUkKLS0tIEpoKzZMQm9Bb2NMWW94dWFMYTlY
            M25ReVE2ZXpZdmtKRnNCOHFWWU9hVjgKSJJ6ddhkHm4B2CToeJYijez04JMYEQBx
            eo4ge7I8iwe35/yzR9kL4Q/Sh1P7c2UXmmH5le1KurzJUjmRx242dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T20:13:55Z"
    mac: ENC[AES256_GCM,data:NglK+vCFqFa7tFZenbqBJOMpMvfGtloWLyyXSXAea8WRfUEebze5WTPk3kp92o2DtY2MxwAojYjUnd+BjeEdWeNPyTpgyES3RDEIQExA7AbulqlEtH2FnLfY1TApCDcMcb2QY/oQgK6/no5wdVKtGlcSqmJd/2lVPzt5SKniejc=,iv:rP1Q8j1QBhvJa+lH7zUId7gSk0yYMn79PvCxRr0qCME=,tag:FM4wA6qgY9akzyZJJsG2pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
