apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:odgSD1cCa5OMqWHj/BhRH9JcXtHO1tL9nD5hi7C4Qp1oDgZsGj875g==,iv:Qu2OVFXMTKYQcnt06xHHvz/Usn3FZgXg3Fj5nlJWBHs=,tag:ZW42p56fo/Vq3OFvLUxSdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ1lETFg0V1FNclhVUm5Q
            M0RTdTJBRFg1MnVhTEVpTW84YnlsdGhaVkZBClRkdFNWM29acFdSVnRFOWo1ODQ2
            c1RzZ3c4WndVMEhXNWVZYjdvTWJ1bEUKLS0tIGxUL0lwZ1QvYUVaOTljSkc5VTBs
            WTFjbmhPR0xsaUcwS3RYQTU3UWxyRTAK/6uuIu6+R9+sBMf1Pyv6W7wxNRC0eV7w
            e4xpUD1EdS5HGzFKYjNnlBDuzRmcKSdxwXWsr0SOA6w91HD+VLB0Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T19:45:23Z"
    mac: ENC[AES256_GCM,data:6PXRjaU41KT/9EmdRS7oP3VyluXXyzqS7oTBH1VukmXDnMwtb4ihvyqec3zVURc8Be4H0/Or6QHLjXQUPHMpDEkhUrRkb/MNYm1hzH7NywWNRqXlY7LcrLWUiH53VJRRAFPJ6ztE15MBRMMIyAcpHkLPC6tkyMPyE+BLBS7kxmc=,iv:+kXNwVjwCiKMu2qpElwD8bh82QxQUdgxncoUt45iWDE=,tag:v8ovfZGaax37I+Keru5etw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
