apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:haNEfXB6u3+bqgdvt+i1w2XofOsUMnN4hAPy3pt7iSmpwL0WB0TD3Q==,iv:h6CBmliyAlfrhODZFFmdgKjQH8RS88D2sCuf/nHegI0=,tag:vIAf2vziNnzPt5vCXyFLag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrqhw9ustrrrecam3gd0wnv759pmewlat89yxa0va2ahgjltaquqne089w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ282b3FYVks2RG5WSTdN
            WUhsellYc2RTZUFXS2k1VkU1S2djd2lZWGhFCnhBSE5RcXlLdDJyNngrNHBDMWNU
            aVlrYmhUd0FqSUEwN1FDaENRb3FJVHcKLS0tIFRsSllkSzlNdkxZWTBxZVFkRHZw
            L1VIMUorQUl1TGZ4QkkyL0JZZnlFNVUKSHngbKBuzQ/CIS5wVnhs7GvFpT5lj5B0
            xMg6sz/rCk4OjFeuRRcMdFBdMoFWFvTE2QrgIAWb4LgDmTA2H28xIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T19:42:52Z"
    mac: ENC[AES256_GCM,data:3QsfmblCXCFD0nSbQ+VQbde5pa4NKBNVIAzQaTgaqq29r+pyCWRNVGVPLni3Ixb3OPZLyMgy4A0N0VpXsx+JGGaTUyXrkSVjznGd9Wt3aRnVmFyRgMjVL3QIASVx0bel2jTD95wJH+IqTJFaU0j5hFM95TuW0Ym/a1mEooaVam8=,iv:jwQK0ib4WvC+/+sx8BmG4sUdkWbP/sZqiThhFHCWGvU=,tag:/y+z6vn0ArclmYjEhCWXmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
