---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./openebs-localpv/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
